### ISSUE TITLE
Data summary statistics

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/Pantheon#1]
Statistics on Pantheon data, required for 'Statistics' menu of site:
- Total number of species in Pantheon
- No. in each class (e.g. Insecta) and no. in each insect order (Coleoptera)
- No in each Osiris broad division
- No in each ISIS BAT
- Total number of traits and other associations

**Comment by HDean** [comment]
Jon W's mock-up of the summary statistics he would like to have on Pantheon
[20160812_SummaryStatisticsTable.docx](https://github.com/BiologicalRecordsCentre/Pantheon/files/417724/20160812_SummaryStatisticsTable.docx)

**Comment by johnvanbreda** [comment]
Proposing this is set up as a static page as it contains value added information that cannot be easily autogenerated.

**Comment by johnvanbreda** [comment]
Ok, what I have just done is add a new type of content to the Drupal site so you can add an entry for each row in the table and edit them in future as needs be. Hannah, you should have rights to go to Content > Add content > Summary table taxon group, then enter the 4 column values and press save. The direct link to the add content page is http://www.brc.ac.uk/pantheon/species-index#overlay=node/add/summary-table-taxon-group. 
I've added the first 4 as a test. You can see the results at http://www.brc.ac.uk/pantheon/statistics. We have the option to add further tables and text to this page in future.

**Comment by HDean** [comment]
Taxon groups now added to statistics page.

**Comment by johnvanbreda** [comment]
@HDean Does this need any introduction at the top of the page and where should it sit in the menu?

**Comment by johnvanbreda** [comment]
Additional comments from Hannah:
I’ve just been editing the statistics page and have now added all the taxon groups. Couple of things I would like to be able to do:

•         Order the table in ascending alphabetical order (currently it is in descending alphabetical order).
•         Add some additional information that would not fit within the current table structure. Jon would like the number of species within the ISIS SATs, the broad biotopes, the habitats and the traits/resources to be visible too. Is that possible on the same page?

**Comment by johnvanbreda** [comment]
I've changed the sort order.
Regarding the extra columns, is it OK to just add new columns for you to fill in as follows:
1. Number of species in ISIS SATs (integer)
2. Broad biotopes (text)
3. Habitats (text)
4. Resources (text)
5. Other traits (text)

Is that the right structure? Also do we need to consider whether to automatically generate these values in the report from the data? Please note that autogenerating the output would not be a trivial task but I can estimate the effort required for it if you think that doing it manually will not be manageable..

**Comment by HDean** [comment]
Hi @johnvanbreda 
Apologies, never replied to this. Could you add in those extra columns and I will populate them.
Thanks, Hannah

**Comment by johnvanbreda** [comment]
Hi @HDean 
Having looked at this again, I think this wasn't a request for additional columns on the "Summary table taxon group" content type, but a request for new content types and associated tables to appear on the stats page? So we could provide the following:
1) A content type called "Summary table SAT" which has a title (the SAT name), code, plus an integer field for the number of species. This then appears as a second table on the Statistics page.
2) Additional content types and tables for the other things you are requesting but I'm not 100% sure what you are expecting.

Can you provide a bit more explanation as to what you expect the output to look like so I can get the structure right please?

**Comment by HDean** [comment]
Hi @johnvanbreda 
You are quite right - what we need are several content types - I think 2.
1. One for the SAT summary table where I can add the name of the SAT, its code and the number of species within the SAT.
2. Similar to the SAT summary but this one for Osiris. So a table where I can the Osiris trait, what type of trait it is (broad biotope, habitat, resource, etc) and the number of species within the trait.

Actually, they could be combined into one - so a column for component/module, trait, code, number of species. It might make it more flexible as it would also allow things like the ecological guilds to be added as well.

**Comment by johnvanbreda** [comment]
Done. There is an example bark & sapwood entry which you can remove or update.

**Comment by HDean** [comment]
Hi @johnvanbreda 
I don't seem to be able to see the content type (Summary table SAT or Osiris trait?). Do you need to add permissions for me to add or edit this content type?

**Comment by johnvanbreda** [comment]
Hi @HDean that should now be sorted.

**Comment by HDean** [comment]
Hui @johnvanbreda 
I can now access the content type but some of them are not showing on the statistics page. I have added the SATs ok and they all appear but I have just added the Osiris broad biotopes and none of them are showing up.

**Comment by johnvanbreda** [comment]
@hdean Now fixed.
