### ISSUE TITLE
Include source references within Lexicon/Help pages

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/Pantheon#10]
Remaining questions:
- Do we want to link data directly to references (e.g. Based on taxon group, assemblage/trait type)?
- If so, do we need a formal bibliography module added to the Drupal site to store information?  Or stored in the Indicia database?

**Comment by HDean** [comment]
Bibliography page now added: http://www.brc.ac.uk/pantheon/content/bibliography

Basic page for now. Unlikely to link directly to data.
