### ISSUE TITLE
Conservation status species incorrectly calculated in Associations table

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#102]
The number of species with Conservation status is being incorrectly calculated in the Associations table - they are being over-counted, but I can't see a pattern that might explain why.

**Comment by johnvanbreda** [comment]
Fixed. The conservation count was wrong generally because it was counting designations, not species with designations. In the associations report it was worse because it was counting an extra designation per synonym.
