### ISSUE TITLE
Species table duplication

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#103]
From "Habitats & resources: tabular: sample ID 13" I opened the SATs tab, where it correctly shows that there were 10 species in this sample associated with SAT W324. If I click on the reddish link for "10" as the Count, I get a table showing 10 species in 11 rows, with Hylaeus pectoralis duplicated:

![image](https://cloud.githubusercontent.com/assets/16039111/22627254/5c63850c-ebb7-11e6-935f-18288f161c62.png)

Also, the SATs table says that there are 11 species in this SAT that have a conservation status, which can't be right because there are only 10 species in total, but in fact only four of them have a conservation status as far as I can tell.

**Comment by HDean** [comment]
Hi @kitenetter 
Is this duplication still happening? I haven't been able to replicate it.

**Comment by kitenetter** [comment]
I haven't seen duplication happen on the live site yet, but of course there aren't very many samples on the live site, and not sure if I should still be uploading dummy samples now we've gone live? I do have some genuine samples that I can try uploading.
