### ISSUE TITLE
Update guild information for caddisflies

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#105]
Awaiting data from Ian Wallace on nectivorous caddisflies, feeding guild data table to be updated if information arrives in time.

**Comment by HDean** [comment]
Hi @kitenetter 
When do you think this data will be available?
Thanks, Hannah

**Comment by kitenetter** [comment]
@HDean decision from Jon based on info from Ian is that **all** caddisfly (Trichoptera) species should be given a new feeding guild category of "possible nectivore".

**Comment by HDean** [comment]
@kitenetter 
Is this for adult or larvel feeding guild or both?
All adult guilds are currently "does not feed" - does this need to change or just the larval guilds?

**Comment by kitenetter** [comment]
@HDean Sorry, I should have said. This change applies only to the adults, which should change from "does not feed" to "possible nectivore". No changes required for the larvae.

**Comment by HDean** [comment]
Data updated. Changes won't show up until the Access database is imported.
