### ISSUE TITLE
Incorrect IEC scores

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#106]
Some IEC scores are given incorrectly in Pantheon. The reported errors all apply to the old version of the IEC. Awaiting table from Jon Webb so we can cross-check them.

**Comment by kitenetter** [comment]
@HDean I have revised IEC tables from David Heaver, will catch up with next time I'm in to see how best to make use of them.

**Comment by kitenetter** [comment]
Revised IEC table passed to @HDean

**Comment by HDean** [comment]
IEC and RIEC updated in the Access database. Will be updated when the data are next imported.
