### ISSUE TITLE
Question: user management of samples

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#107]
We have been asked to ensure that users can 'manage' their own samples, which I take to mean filter, edit and/or delete samples that a user has added.

Filtering can be done via the main Filter on the Explore all samples page (Add filter - Who - My records).

Will we be able to edit samples that have previously been added, e.g. to add or remove a species, or to change a grid ref?

Will we be able to delete samples that we have added?

**Comment by HDean** [comment]
Comment by Jon Webb:

After using the paste tool a number of times now, I have realised that was is needed is a ‘delete list’ button. It is a good way to clear out all those lists that, for one reason or another, were tests, contained errors etc.

**Comment by HDean** [comment]
Closing as it has been superseded by other issues.
