### ISSUE TITLE
User account management

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#108]
Users need a way of editing their account, e.g. to change email or password.

**Comment by johnvanbreda** [comment]
@kitenetter Shall I add My Account to the menu, next to Logout?

**Comment by kitenetter** [comment]
@johnvanbreda that would be good, but am I being daft here - is there already a link in the top-right corner of the screen? There is for me but I'm logged on as an admin, not sure how it appears for others:

![image](https://cloud.githubusercontent.com/assets/16039111/22936792/77a8de84-f2ce-11e6-9491-3745d89e52d9.png)

If there is already a link in the top-right (similar to the one in iRecord) then that should be sufficient.

**Comment by johnvanbreda** [comment]
I've added a link to the main menu - the black bar across the top is only shown for admins/site editors.

**Comment by HDean** [comment]
"My account" now present on the main menu
