### ISSUE TITLE
Standardise date formats

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#109]
Most date formats are dd/mm/yyyy, but not all, e.g. Results overview is yyyy/mm/dd:

![image](https://cloud.githubusercontent.com/assets/16039111/22700188/ac7ce54c-ed51-11e6-96d2-b8e2d5e7a025.png)

**Comment by HDean** [comment]
Hi @johnvanbreda 
Although not an error as such, it would be good if this could be sorted out as a high priority?

**Comment by johnvanbreda** [comment]
Fixed in code and will be released next time code is updated.
