### ISSUE TITLE
Hierachical boxes: show that headings are clickable

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#110]
In Habitats and Resources: Hierarchy it is not obvious that the boxes can be clicked to open up the next level down in the hierarchy - make the headings blue and underlined?

**Comment by HDean** [comment]
@johnvanbreda 
This works well except that the last box in the link is also blue and underlined. Is it possible to make this just black text to show that there is nothing else to follow? I know this might be a tricky thing to do because the end point can be at different levels in the hierarchy.

**Comment by johnvanbreda** [comment]
It is a bit tricky because we don't know if there are any children until you try to load the children. We could include a count of children in the query but my initial tests of this show it might be tricky not to reduce the performance quite a bit.

**Comment by HDean** [comment]
Hi @johnvanbreda 
Would putting an extra column in the Traits table, as a label highlighting which resources are at the end of the hierarchy and therefore have no children, help with this? I.e. would it be easier to have a statement in the code which says don't display in blue underlined text/hyperlink is the column has a value?
