### ISSUE TITLE
Clarify numbers in "Basic output"

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#114]
Using this example:
http://www.brc.ac.uk/pantheon/pantheon/summary?dynamic-sample_id=678556&dynamic-sample_type=sample

![image](https://cloud.githubusercontent.com/assets/16039111/22701358/5d4d931e-ed55-11e6-8ea6-4cfa247895a2.png)

- "Sample size" would be clearer as "Number of species in sample"
- "Number analysed" is given as 19, but in fact only 18 species in this particular list have data attached to them as far as I can see - but I'm not sure what is controlling what gets dropped from the total sample
- "Not analysed" is given as four, all of which lack data, but a fifth species (Tineola bisselliella) appears also to be lacking in data, not sure why it isn't included
- "% return" would be clearer as "% analysed"

**Comment by johnvanbreda** [comment]
* Sample size changed to Number of species in sample
* The species are counted as analysed if they have any Pantheon information attached to them, even if that info does not appear in the species list table output. In this case, Tineola bisselliella has the keywords synanthropic and in buildings so it is counted as analysed. I'm not 100% sure if this is correct behaviour.
* As above.
* % return changed to % analysed

**Comment by kitenetter** [comment]
Thanks @johnvanbreda 
I think that behaviour is okay, main thing is that the explanations in the Help/Lexicon pages explain what is happening.

Only other question is what happens to species that have a conservation status, but no habitats/traits data - do they count as being analysed or not?

**Comment by johnvanbreda** [comment]
Currently, no having a conservation status does not count as being analysed. This could of course be changed.

**Comment by kitenetter** [comment]
I think we can leave it as it is at the moment, I just need to ensure that it is explained correctly. 

There is potential for confusion when different numbers of species are contributing to different parts of Pantheon, and I do wonder if the best long-term solution would be to count all species at all times, but code them to a "no data available" category if they haven't been linked to anything. That way every list in Pantheon would be starting from the same set of species, and it would be obvious which ones had data in which tables. But that probably needs discussion and is for the longer-term. Let's stick with what we're doing at the moment.

**Comment by HDean** [comment]
@johnvanbreda 
In the example, Tineola bisselliella being counted as analysed is correct behaviour. It is only because the species list doesn't show the "tabular - other" data that it appears it doesn't have data.
