### ISSUE TITLE
Information buttons missing

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#116]
In Species list tables, the "i" buttons get missed off if there are multiple entries in the biotope and habitat columns, e.g. Tipula vittata in this example:

![image](https://cloud.githubusercontent.com/assets/16039111/22714389/2af5c902-ed84-11e6-9d92-c797b6602fec.png)

**Comment by johnvanbreda** [comment]
Fixed.
