### ISSUE TITLE
Remove "Habitats & resources: species list"?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#119]
From the Combined summary options it is possible to select "Habitats & resources: species list". However, this table does not include anything that is not available in the "Species list" option, and in addition its layout is inconsistent with the other tables (e.g. concatenation of Order and Family; and the resources are not presented in a proper hierarchy so that "soil humidity" and "dry" are separated.

Suggest removing the "Habitats & resources: species list" option.

**Comment by johnvanbreda** [comment]
I agree - confirm with Jon/Hannah?

**Comment by kitenetter** [comment]
It was Jon who initially queried whether we need this report (following queries over its format in the peer-review process) so as far as I'm aware there is consensus that it isn't needed.

**Comment by johnvanbreda** [comment]
Done
