### ISSUE TITLE
Implement ISIS-thresholds for CSM

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/Pantheon#12]
1. Add flag on data entry to indicate if sample/species list represents an 'ISIS-compliant' dataset or 'Partial'.  Default value is 'No'?
2. Use for flag to determine if CSM Assemblage scores are shown or hidden (by default, CSM assemblage score is not shown).  If 'No' then no CSM Assemblage score given in results

**Comment by HDean** [comment]
I'm closing this as I think it is done. These are the thresholds which state whether the SAT is favourable and unfavourable. This information is currently available through the Osiris tabular view on the SATs tab.
