### ISSUE TITLE
Correction to associations

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#122]
This association needs correcting:
![image](https://cloud.githubusercontent.com/assets/16039111/22830424/692d3e28-ef9e-11e6-8eb5-631554630fe7.png)

At first I was worried that some data had got misaligned, but David Heaver informs me that it is just an error in the raw data.

- Phasia pusilla should be associated with Heteroptera.
- Gymnosoma clavatum should be associated with Pentatomidae.

**Comment by HDean** [comment]
These have now been updated in the Access database. Hopefully they should be updated on the online version when the data is reloaded.
