### ISSUE TITLE
Minor issue with hierarchical display

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#124]
When the hierarchical display reaches a fifth level it gets shunted to the foot pf the page (using Chrome). Not a major problem, it's still legible and understandable.

![image](https://cloud.githubusercontent.com/assets/16039111/22951628/cbe9104e-f301-11e6-83af-a40159776bd5.png)

**Comment by HDean** [comment]
Closing - mentioned this to Jon W - he is not too concerned about this. Maybe revisited in next development phase.
