### ISSUE TITLE
Species list for habitat scores

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#125]
On the report page for the habitat scores it would be great if the numbers against each score were clickable to open the relevant species into a table. (No need to do likewise for the conservation status as they are available elsewhere.)

This is low priority though, as the scoring species can always be filtered out from a download of the sample's full species list.

**Comment by Davydaveth** [comment]
This request has been repeated by another user who has spent far too long having to manually manipulate his sample output to find the species contributing to a particular index value.
