### ISSUE TITLE
Combined report hyperlinked numbers producing empty lists

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#127]
In the combined report page, the hyperlinked species totals are opening up a species table but not populating the table with any species. This applies to the clickable numbers in all the tables with the exception of the "Other classifications" tables.

**Comment by johnvanbreda** [comment]
@kitenetter I've not managed to reproduce this - can you give me some details please.

**Comment by kitenetter** [comment]
@johnvanbreda My starting point is the combined summary page for one of of my scratchpad samples, with boxes ticked for all reports:
http://www.brc.ac.uk/pantheon/display-node-list?dynamic-sample_id=22&dynamic-sample_type=scratchpad&include=%5B%22417%22%2C%22337%22%2C%22338%22%2C%2290%22%2C%2287%22%2C%2266%22%2C%2267%22%2C%22422%22%2C%22423%22%2C%22424%22%2C%2271%22%2C%2270%22%2C%2268%22%5D

I've just tried clicking on the number 13 in the species count column:

![image](https://cloud.githubusercontent.com/assets/16039111/22974241/4d2f2ad6-f379-11e6-9314-d8e89da25527.png)

A species table opens, but is empty:

![image](https://cloud.githubusercontent.com/assets/16039111/22974252/5cce6e16-f379-11e6-831a-f0d8c0d885ba.png)

**Comment by HDean** [comment]
@johnvanbreda 
I also get the same problem (I am using scratchpad sample ID 24). The only place where the species tables open empty is within the combined reports and also the results overview.

**Comment by johnvanbreda** [comment]
Thanks - it was related to scratchpads specifically. Now fixed.
