### ISSUE TITLE
Error messages from scratchpad

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#128]
Tried using scratchpad on 26 Feb 2017. My scratchpads page has error:

> Warning: A non-numeric value encountered in iform_dynamic::get_form_html() (line 278 of D:\web sites\drupal7\sites\www.brc.ac.uk.pantheon\modules\iform\client_helpers\prebuilt_forms\includes\dynamic.php).
> Warning: A non-numeric value encountered in iform_dynamic::get_form_html() (line 278 of D:\web sites\drupal7\sites\www.brc.ac.uk.pantheon\modules\iform\client_helpers\prebuilt_forms\includes\dynamic.php).

Tried to add new scratchpad, pasted in species, clicked on "check", error:

> Normal 0 false false false EN-GB X-NONE X-NONE /* Style Definitions */ table.MsoNormalTable {mso-style-name:"Table Normal"; mso-tstyle-rowband-size:0; mso-tstyle-colband-size:0; mso-style-noshow:yes; mso-style-priority:99; mso-style-parent:""; mso-padding-alt:0cm 5.4pt 0cm 5.4pt; mso-para-margin-top:0cm; mso-para-margin-right:0cm; mso-para-margin-bottom:8.0pt; mso-para-margin-left:0cm; line-height:107%; mso-pagination:widow-orphan; font-size:11.0pt; font-family:"Calibri" (match not found) sans-serif; mso-ascii-font-family:Calibri; mso-ascii-theme-font:minor-latin; mso-hansi-font-family:Calibri; mso-hansi-theme-font:minor-latin; mso-bidi-font-family:"Times New Roman"; mso-bidi-theme-font:minor-bidi; mso-fareast-language:EN-US;}
> Phylus melanocephalus (match not found)
> Phylus palliceps (match not found)
> Pterostichus nigrita (match not found)
> Pterostichus rhaeticus (match not found)
> Pterostichus diligens (match not found)
> Pterostichus strenuus (match not found)
> Lithobius borealis (match not found)
> Lithobius lapidicola (match not found)

**Comment by johnvanbreda** [comment]
Fixed. The text pasted had some horrendous formatting code embedded in it, created by Word. 
The page error was a previously existing bug that had no effect but warnings appeared after the recent PHP update. Also fixed.
