### ISSUE TITLE
SQS checks

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#129]
Reminder to check SQS scores following next data update to catch any inconsistancy between scores and status, e.g. Pocota personata is currently scored at 16 but is now only LC/NS status.

**Comment by HDean** [comment]
Hi @kitenetter 
Now the newer version of the database is being used, can you check the SQS scores?
For info, Pocota personata now has a score of 4.
I have just spoken with Jon and he will also check (and also ask Mark Guerney to check as well).

**Comment by kitenetter** [comment]
All seems well so far!
