### ISSUE TITLE
Add 'not-assigned' category to all reports

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/Pantheon#13]
http://www.brc.ac.uk/pantheon/osiris/ecological-divisions?dynamic-sample_id=312083

Add 'not-assigned' category for species within the species list/sample but not assigned to an ecological division

**Comment by johnvanbreda** [comment]
On summary in basic output, add a "not analysed" link to the unused species. Shows the species list filtered to stuff with no Pantheon information. Place this next to Number analysed (also a link).

**Comment by johnvanbreda** [comment]
Done. The not analysed category is calculated as any species in the sample which has no Pantheon traits attached to it at all (from Osiris, ISIS or HORUS). On the original link David posted (http://www.brc.ac.uk/pantheon/osiris/ecological-divisions?dynamic-sample_id=312083) should this actually be the number of species that are not associated with an ecological division even if they have other Pantheon traits? In this example, there are 267 species in the sample, 245 have some sort of trait data and 22 have none whatsoever. By totalling the boxes, I can see 219 have an ecological division, so we could change the "Number analysed" and "not analysed" in the panel above to 219 & 48 respectively?

**Comment by HDean** [comment]
This is complete.
