### ISSUE TITLE
Additional text/image for home page after user logs in

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#130]
Currently when a user logs in, the same information is shown on the home page as is visible before a user logs in. This includes a box that says "Register". The Register box is redundant but what do we put in its place.

Current suggestions:

- photos

- list of users samples/lists

**Comment by johnvanbreda** [comment]
Other suggestions:
Summary data (Pantheon currently covers x species, y traits, z associations etc).
News articles (but would need to regularly update this)

**Comment by HDean** [comment]
Does the list of samples at the bottom need to be there if you are not logged in?
A suggestion:
•	Remove the latest samples list.
•	When logged in, have an “Activity” block, with tabs for All activity and My activity. These show a list of scratchpads or samples, e.g.:
•	Martin Harvey uploaded 305 species for site Wicken Fen on 27/02/2017 View
•	Hannah Dean uploaded 37 species for site Arne on 26/02/2017 View
•	View more...  (takes you to the samples list)

**Comment by HDean** [comment]
@johnvanbreda 
From recent communications from Jon W, he was wondering if we could replace the register panel with a photo. Do you have access to the ones that were used in the previous look of Pantheon. One of those should do.

**Comment by HDean** [comment]
Requirement from work schedule for FY17/18:
Remove registration panel and replace with a smaller photograph.
Remove About; retain latest samples. Add new text dealing with requirement for unified date and grid ref for a sample, and text about “ISIS-compliance”- the user home page should be mostly about data and samples.
Add change-log link here.

**Comment by johnvanbreda** [comment]
@hdean I was wondering if you could mock up what you want the home page to look like when logged in as well as logged out, to save going back and forth to get the text and layout right? E.g. a rough sketch or a Word document?

**Comment by HDean** [comment]
Hi @johnvanbreda 
Please see attached mock-up! Very rough and ready but hopefully it conveys the message! The photo is any random photo of an invert/bug - do you still have the ones that were originally used in Pantheon?
I've tried to show hyperlinked text as blue underlined - these should hyperlink to these pages:
1. instructions - http://www.brc.ac.uk/pantheon/content/how-add-records
2. copy and paste - http://www.brc.ac.uk/pantheon/species-lists/my-list
3. upload a csv file - http://www.brc.ac.uk/pantheon/import-instructions
4. manually enter records - http://www.brc.ac.uk/pantheon/enter-records-list
[LoggedInHomePage.pptx](https://github.com/BiologicalRecordsCentre/Pantheon/files/1572110/LoggedInHomePage.pptx)

**Comment by johnvanbreda** [comment]
Thanks Hannah. A couple of questions:
1. What about when logged out?
2. Having dropped the About paragraph, doesn't there need to be some sort of summary/welcome sentence or paragraph? Just a quick overview of what Pantheon is for?

**Comment by HDean** [comment]
1. When logged out the user sees the current page (About, Register, Disclaimer).
2, When logged in, include the first sentence of the "About" box, with a link to the About Pantheon page (http://www.brc.ac.uk/pantheon/about/pantheon)

**Comment by johnvanbreda** [comment]
Ok, that's done.
