### ISSUE TITLE
Additional metadata for scratchpad

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#131]
A number of additional metadata fields were identified as being desirable by the Pantheon steering group:

- Date: must be able to support date ranges; I would favour having two separate fields for "Date" and "Date To", but if needed we can use the existing vague date functionality as long as our guidance is clear on how to use it
- Uploaded by: this is for the person who is managing the sample in Pantheon, which may not be the same person as the recorder/s who generated the species list (e.g. a site manager may be combining surveys from several recorders to analyse in Pantheon)
- No. of fieldwork days to produce list (this is a simple measure of recording effort)
- Sampling methods used: needs to be a multi-option choice from a termlist (see below)
- Common Standards Monitoring compliancy (TIck-box)

I think we need to make it explicit on this metadata form that by saving the data into Pantheon it is being made publicly available. Suggested wording:
> By saving this sample I agree that it will be visible and available for further analysis within Pantheon and I assign a CC0 licence to the sample data. 

At the foot of the current metadata form we have a statement about using the Enter a casual record form if a sensitive species is involved, but I don't think we are implementing a casual record form are we? So that statement can be removed.

Sampling methods termlist (tick all that apply):
- Free search
- Sweeping
- Beating
- Pitfall trapping
- Pan trapping (= water trapping)
- Suction sampling
- Vane trapping
- Malaise trapping
- Other (please provide detail in Comment box)

**Comment by johnvanbreda** [comment]
I've added the controls except for Uploaded by. @kitenetter surely this is always the same as the logged in user? Would a more useful control be called "List collated by"?

**Comment by kitenetter** [comment]
@johnvanbreda I think we need to store information on who has ownership/editing rights for the uploaded list (which will be the logged in user, so presumably we already have that information); plus who has collated the list (this is likely to be the logged-on user in many cases but not all); plus a recorder name (which may be the logged in user, but many lists will be combined species lists from multiple recorders).

So I agree that having a field for "Species list collated by" would be useful. And for the recorder field, where we currently have explanatory text saying "Enter the recorder's name, if different", I'd suggest altering the text to:
Enter the recorder's name, or use "multiple recorders" if the list has been combined from various sources

Alternatively we could recommend that the recorder name is left blank to indiciate no specific recorder, but I guess it is better to be explicit in stating "multiple recorders".

All this metadata is potentially useful and could enable better analysis and filtering of the lists that we hope people will add to Pantheon, but it does raise the question of how the metadata will be accessed once saved. At some point we'll need to work out how to provides reports or filters that use the metadata, but I assume that would be new work that is outside the current scope.

**Comment by johnvanbreda** [comment]
Ok, those changes are done.
