### ISSUE TITLE
CSV import queries

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#132]
Do we need to offer anything other than "General records" and "UK Master List"? Can those two choices be set as the default options?

![image](https://cloud.githubusercontent.com/assets/16039111/23398207/80cb72f4-fd93-11e6-9413-91afcba482a2.png)

I imported a recorder name into the "Sample - Recorder names" field. This populated the "Surveyor" entry in the "Results overview" page, but the Recorder field in the Pantheon samples table did not get populated.
I imported a recorder name into the "Sample Custom Attributes - Recorder Name" field. This populated the Recorder field in the Pantheon samples table but not the "Surveyor" entry in the "Results overview" page.
Not sure why we need to treat Surveyor and Recorder differently?

Can we add a prominent warning at the start of the CSV import process that A) each unique combination of location, grid reference and date will be treated as a separate sample, and B) your CSV file must be sorted by location, grid reference and date before import, otherwise each change will trigger a new sample even if there are only a few unique combinations.

Having uploaded a sample of 18 records all for the same location, grid reference and date, it still got broken into three separate samples. I can't see an obvious reason in my data for this to happen - there are variations in the comment fields that I imported but they don't seem to match where the sample got broken up.

Should we be encouraging people to upload the minimum number of fields in order to avoid problems with single samples being broken up into multiple batches? If so, can we reduce the number of field matches that we offer, and advise people to stick to the basic species, location, grid ref, date, recorder?

When attempting to import dates based on "Date start" and "Date end", there is a message saying that the "Date" field has to be imported as well. But if you do import into the "Date" field, any entries in "Date start" and "Date end" are ignored.

[It is possible to import a date range as a vague date into the "Date" field (as long as the range is formatted correctly). However, I did not import anything into "Date type" so I'm not sure if the date range will be recognised properly - perhaps that's not a problem within Pantheon, and would only be a problem if we were treating Pantheon samples as full species records, which we're not.]

When importing based on TVKs rather than species names, some common species are not recognised - MH to re-test following move to live server.

**Comment by HDean** [comment]
Closing this - most of these issues have been dealt with - there is now text stating a single location, date and grid ref is needed when logged in and on the import csv page.
