### ISSUE TITLE
Species lists not displaying

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#133]
Using pasted lists (which have not been saved with metadata), if I open a list that I pasted a few weeks ago I can click on the various link to see underlying species lists. But with lists that I've pasted in in the last couple of days, the species list form opens up but just displays an egg-timer and the list does not appear.

**Comment by kitenetter** [comment]
Actually they are displaying, they are just being very slow to calculate.

**Comment by kitenetter** [comment]
Not sure now, one of them did get to a list after a few minutes, but others are showing the egg-timer for at least an hour.

**Comment by HDean** [comment]
Hi @kitenetter 
Have you checked this out again recently? I have just copied and pasted a list of species and am having no trouble getting the species lists to show. I'll try again later and then maybe in a day or two to double check.

**Comment by kitenetter** [comment]
I'm still finding them a bit variable in how quickly they load but haven't had any complete freezes on the live site. Will close this issue for now.

**Comment by johnvanbreda** [comment]
I made some changes to the reporting code yesterday - now much faster.
