### ISSUE TITLE
Breadcrumb trails need updating

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#135]
Some pages linked from the "About Pantheon" section have breadcrumb trails that include mention of OSIRIS, e.g. on this one:
http://www.brc.ac.uk/pantheon/content/broad-resources

![image](https://cloud.githubusercontent.com/assets/16039111/23794915/bd7bdbfe-058a-11e7-9589-1240426b7900.png)

**Comment by HDean** [comment]
@kitenetter , @johnvanbreda ,
This appears to be corrected now - perhaps it resolved itself when moved to the live server? Or perhaps John has corrected it?
Martin - can you check that this has been resolved and close the issue if you are happy that it is done.

**Comment by kitenetter** [comment]
Yes, seems to be fixed now.

**Comment by johnvanbreda** [comment]
Also corrected during the live switchover!
