### ISSUE TITLE
Glossary display needs correcting

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#136]
We have changed from Lexicon to Glossary, and the new Glossary page is displaying the wrong set of information - the terms are there but we've lost the labels, and we have added information about authorship and updates that isn't needed. The search function has gone missing as well,
http://www.brc.ac.uk/pantheon/glossary

**Comment by HDean** [comment]
Hi @kitenetter ,
I have checked again this morning and it all looks correct, so I am going to close this issue. Please reopen if you think otherwise!
Thanks, Hannah

**Comment by johnvanbreda** [comment]
Yes, I fixed this yesterday during the live migration.
