### ISSUE TITLE
Terms for Habitat scores

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#137]
Some of the habitat score terms have been edited and no longer match the terms used in the species list tables, nor to present results on the Habitat scores page - are we able to easily realign these or does that depend on what data has been uploaded?

If we can't easily change them, can we add an information button to these terms so that they link to the correct place in the glossary?

**Comment by johnvanbreda** [comment]
Fixed - there was a default view called Glossary which was overriding our version.
