### ISSUE TITLE
Enhance Horus report

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/Pantheon#14]
e.g. http://www.brc.ac.uk/pantheon/horus/quality-scores-overview?dynamic-sample_id=312083
- HORUS conservation score to be removed.
- Relabel 'Number of species recognised' to 'Number of species with Horus coding'

**Comment by HDean** [comment]
This will also include the Horus scores

**Comment by johnvanbreda** [comment]
Done

**Comment by HDean** [comment]
Hi @johnvanbreda 
I've noticed that in the Horus report, the second in the overview table says "Number of species with Horus coding". Can you change this to "Number of species with habitat scores" for me please?

**Comment by johnvanbreda** [comment]
Done
