### ISSUE TITLE
Pasted species lists not showing in "Explore my samples"

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#140]
When a species list has been added to Pantheon via the "pasting species lists" method it does not show up in "Explore my species lists" when no metadata has been added and the sample saved. Is there anyway it could be?
The only way to find the pasted species lists is to go through to "pasting species lists" again.

**Comment by johnvanbreda** [comment]
We can't show the pasted lists on the Explore my samples page because of the lack of metadata (no columns would have anything to show).
The pasted lists are as you say available under the paste species lists menu item. Perhaps the menu item name is not clear enough?

**Comment by HDean** [comment]
Okay, that makes sense. I think the best way to get around this is to provide a user guide of how to use Pantheon and include a section on getting access to saved lists with metadata and the saved lists on the scratchpad.

**Comment by HDean** [comment]
Added new user guide to Help menu
