### ISSUE TITLE
Changes to Habitat Scores terminology

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#141]
A review of the glossary and the habitat scoring system within Pantheon has highlighted some inconsistencies that need fixing:

1. In the glossary, the tag "quality index" should be changed to "habitat score"
2. Update the species index so that the heading "Published indices" is changed to "Habitat score"
3. The output for ERS (B) should be changed from numerical to text, so that so “1” will become “ERS dependent”, “2” will become “ERS associated”

**Comment by johnvanbreda** [comment]
@hdean 2 questions:
1) Is it OK to change the ERS (...) names to ERS (Diptera) and ERS (Coleoptera)? This makes more sense to me and matches the glossary.
2) The ERS diptera score outputs replaced the original Drake and Hewitt outputs. The reports still map te various values according to this - so value 5 for example shows "tourist". Should the mappings actually use the ones in the glossary instead, i.e.:
    Fidelity score 1: total fidelity (11 species)
    Fidelity score 2: strong fidelity (20 species)
    Fidelity score 3: moderate fidelity (54 species)
If so, what about scores 4 & 5 which are not in the glossary?

**Comment by HDean** [comment]
Hi @johnvanbreda 
1. Yes, it is okay to change the ERS names to ERS (Diptera) and ERS (Coleoptera). 
2. Yes, use the glossary terms instead. There shouldn't be any 4 or 5 scores in the data now, so terms are not needed for these. The 4 and 5 scores were provided in error and shouldn't have been in Pantheon.

**Comment by johnvanbreda** [comment]
Are you sure the diptera scores are right then?
```
select * from pantheon.tbl_species_traits where trait_id=391 and trait_value>'3'
```
gives over 60 records which have a score of 4 or 5.

**Comment by HDean** [comment]
Hmm, okay, there shouldn't be any. Perhaps I sent you the wrong replacement list for ERS Diptera? Correct file attached. There should only be values 1, 2 and 3 in the TraitValue column.
[20170320_ERSDiptera_New.xlsx](https://github.com/BiologicalRecordsCentre/Pantheon/files/879424/20170320_ERSDiptera_New.xlsx)

**Comment by johnvanbreda** [comment]
Ah - thanks - I realise now that when I ran the update script it didn't clear the old values out. Now fixed.
