### ISSUE TITLE
Confusing subheading in Assocations table

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#142]
In the associations table for a large scratchpad sample that I have pasted in, there are the usual headings for Animalia, Fungi and Plantae, but underneath Plantae is another subhead for "Plants", and under that subhead are a range of things including some animals ("Symphyta", "Heteroptera" etc.), and in addition the sections for Plantae and Fungi reappear under the "Plants" subhead.

I don't recall seeing this before the latest updates.

**Comment by johnvanbreda** [comment]
Can you let me know the scratchpad ID please @kitenetter?

**Comment by HDean** [comment]
Hi @johnvanbreda , @kitenetter ,
I see the same thing, on a sample which is not on the scratchpad. Sample ID 2291535 (site name Highgate Common). On the Associations page, I get the expected output but right at the bottom there is another section titled "Plants" and then it lists in separate tables a number of associated taxa (in this case Plantae, Fungi, Acari, Algae, Bombus (Thoracombus) muscorum, Lichens, Polypodiales, Pteridium aquilinum).

**Comment by johnvanbreda** [comment]
Fixed.
