### ISSUE TITLE
Choice of fields for species list - odd display

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#144]
This is not a major issue, but does seem to be new - from the Species list table, when you go to choose the fields to display, the "i" buttons have become part of the field names: "statusi" "biotopei" etc.

![image](https://cloud.githubusercontent.com/assets/16039111/24495439/09e15616-152d-11e7-8c8c-677eec868b1d.png)

**Comment by HDean** [comment]
Hi @johnvanbreda 
Another high priority one!

**Comment by johnvanbreda** [comment]
Fixed in code and will be updated next time code is released to the live site.
