### ISSUE TITLE
Grazing marsh species status score not correctly calculating

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#145]
This is based on checking the "grazing marsh- species" score for this sample:
http://www.brc.ac.uk/pantheon/horus/quality-scores-overview?dynamic-sample_id=2281670&dynamic-sample_type=sample

Pantheon gives the score as 9.05, whereas it should be 1.86. The calculation should be a sum of all scores for the species that have a "grazing marsh- species" score, divided by the number of those species. In the link above there are 22 species with a "grazing marsh- species" score, and the scores add up to 41:

![image](https://cloud.githubusercontent.com/assets/16039111/24496665/bceb2b9e-1530-11e7-8f60-10564e049b74.png)

**Comment by HDean** [comment]
Hi @johnvanbreda 
Can this error be looked at as a priority please. Martin has provided the correct calculation above. Further information, which agrees with Martin, has been provided by David H:

Within a sample, the taxa are matched against the master list, the matches selected and the scores are summed. This sample summed score is then divided by the sample size to give the coastal grazing marsh conservation score. Values for this index typically hang around 1.3, with SSSI quality considered to be expressed around 1.5. It is doubtful it could ever exceed a value of 2.

**Comment by johnvanbreda** [comment]
Fixed in code and will be deployed next time warehouse is updated.
