### ISSUE TITLE
SATs showing unusual behaviour

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#146]
@johnvanbreda 

For sample ID 2291535, I was just looking at the SATs output and noticed that sometimes the habitat and SAT are shown in the SAT column together but sometimes they are split into the habitat and SAT column.

![image](https://cloud.githubusercontent.com/assets/17744201/24664583/f60aa636-1952-11e7-9cf6-844f979f181d.png)

Interestingly this is also a duplication for species Bryophila domestica! It is the only one doing it in the sample.

Also, can the SATs that sit within a broad biotope (rather than habitat) not show the broad biotope within the SATs column, for example, the rich flower resource SAT is not prefixed with "open habitats >>"

![image](https://cloud.githubusercontent.com/assets/17744201/24664814/831f61c4-1953-11e7-950f-dbf8ba9ee253.png)

**Comment by HDean** [comment]
Hi @johnvanbreda 
Although this was not on the original work schedule, could this be looked at as a priority. I did factor in some contingency to your time luckily!

**Comment by johnvanbreda** [comment]
This is the same underlying issue as https://github.com/BiologicalRecordsCentre/Pantheon/issues/175. Fixed in next release.
