### ISSUE TITLE
Add "delete" option within My species lists

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#147]
@johnvanbreda 
When looking at the pasted lists within "My species lists", can "delete" be added to the actions box.

**Comment by HDean** [comment]
Hi John,
I've realised that the delete an entire list requirement was already in GitHub!
Thanks, Hannah

**Comment by johnvanbreda** [comment]
Done

**Comment by HDean** [comment]
Hi @johnvanbreda ,
The delete option is there but it doesn't seem to delete anything!

**Comment by johnvanbreda** [comment]
It does for me - which browser are you using and which list are you trying to delete?

**Comment by HDean** [comment]
I'm using Google Chrome (Version 64.0.3282.167). I've tried deleting all of my combined pasted species lists and one of the single pasted lists. It gives the dialogue boxes suggesting it has deleted them but when I refresh or log out/in again, they are still there.

**Comment by johnvanbreda** [comment]
A permissions thing. Now fixed.
