### ISSUE TITLE
Add warning when adding metadata to pasted list that when saved the list becomes public

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#148]
When metadata is added and saved to a pasted species list, the list becomes public. This is not obvious, therefore, either the "Add metadata" link becomes "Add metadata and make public" or a warning box needs to show when the "Add metadata" link is clicked that says something along the lines of "By adding metadata and saving, your sample list will become public within Pantheon".

**Comment by HDean** [comment]
Hi @johnvanbreda 
Again, not on the original work schedule but hopefully this might be easy to do? It would be good to provide this warning as I think it has caught a few people out.

**Comment by kitenetter** [comment]
In #192 I've suggested using "Save to public database" for what we currently call "Add metadata", but I agree that some further explanation on the form that subsequently opens up (or a link to a glossary entry) would be helpful.

**Comment by johnvanbreda** [comment]
Link text updated and text adding to the top of the data entry form.
