### ISSUE TITLE
Broad resource "dung & carrion" missing?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#152]
I can't find any way of getting the "dung & carrion" broad resource to display or download, am I missing something?

**Comment by HDean** [comment]
Hi @kitenetter 
When you say you can't find any of getting dung& carrion to display, is this part of a sample analysis or just through the Species Index?
The broad resources aren't visible via the Species Index (which I think is an oversight) but they should be showing in the hierarchy and the tabular - other outputs.

**Comment by HDean** [comment]
Also good point about the downloads!

**Comment by kitenetter** [comment]
Can't find them in Hierarchy or Tabular - this is for a scratchpad upload that contained quite a lot of dung beetles, which I assume to be linked to the dung & carrion broad resource, but I haven't double-checked that there is a link in the database.

I haven't saved my scratchpad list, so not sure if you can see this:
http://www.brc.ac.uk/pantheon/osiris/hierarchy?dynamic-conservation_group_id=&dynamic-sample_id=50&dynamic-sample_type=scratchpad

http://www.brc.ac.uk/pantheon/osiris/tabular-other?dynamic-conservation_group_id=&dynamic-sample_id=50&dynamic-sample_type=scratchpad

![image](https://cloud.githubusercontent.com/assets/16039111/24703589/b6724656-19fb-11e7-921e-d751d81373b0.png)

**Comment by HDean** [comment]
Hmm, this is interesting. I have tried it with a saved (test) dataset and can see the broad resource "dung & carrion". It might something to do with it being saved on the scratchpad but I don't see why it would differ. I will check some of the species to make sure that they are definitely typed to dung & carrion.

**Comment by HDean** [comment]
Okay, I think I know what might be happening. There are species typed to dung & carrions >> dung but these show within the resources (as in biotope>habitat>resource) not the broad resources. However, the output for dung & carrion was supposed to show all species typed to dung & carrion rather than just the broad resource ones. It had been fixed but appears to have been lost again.

**Comment by HDean** [comment]
Hi @johnvanbreda 
Can you investigate this for me please? It appears that dung and carrion are not showing correctly again. Dung and carrion are correctly showing within the biotope>>habitat>>resource hierarchy, and the broad resource for dung & carrion is also showing. However, they are not showing combined, i.e. the resources dung and carrion are not showing up in the tabular - other/broad resource report.

**Comment by HDean** [comment]
Hi @johnvanbreda 
Another high priority one! Thanks.

**Comment by johnvanbreda** [comment]
Fixed in the next release of the code.
Although we had fixed this, the fix was based on resources which had no parent, but we subsequently fixed them so they did have parents which undid the fix. Now dung & carrion is treated as a special case.
