### ISSUE TITLE
Change text on home page

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#154]
The first bit of text currently says:

"Pantheon is currently a beta version, with further analysis options and support information planned to be incorporated over 2017."

Change to something a bit more inclusive to users, something like:

"Pantheon is currently a beta version, with further development planned for 2017. The Pantheon team welcomes feedback, which you can send via the various methods on the Contact page."

**Comment by HDean** [comment]
Requirement from work schedule for FY17/18:

Retain About text which explains what the database is. Retain Register panel to allow users to join. Remove latest samples. 
In the latest samples place, add Disclaimer link (moved from down from higher in the page. Cut part of the About Pantheon text into this front page, which starts “Pantheon is overseen by a steering group….

**Comment by johnvanbreda** [comment]
@hdean I've changed the text at the top of the home page as per the first comment. Is it clear enough where to find the Contact page though - should the text mention that it is found on the About menu?

In place of the latest samples, shall I move the whole sentence containing the disclaimer link: "It is essential that you read the disclaimer before using Pantheon."? What about the other sentence in this paragraph (starting This information...) - does this stay in the About section or should it also move down the page?

Is it just the following text that should move from the About page to the bottom of the home page, or should any other text on the About page go with it? I.e. where should the bit I cut out end?
"Pantheon is overseen by a steering group that includes representatives from Buglife, RSPB and academia. Further modules will be added to Pantheon as and when these are submitted and approved by the steering group."

**Comment by HDean** [comment]
1. Can you hyperlink the "Contact page" to the contact page? I wouldn't worry about this too much as this will probably be removed soon... And can 2017 be updated to 2018?
2. The "About" box should read: Pantheon is an analytical tool developed by Natural England and the Centre for Ecology & Hydrology to assist invertebrate nature conservation in England. Users import lists of invertebrates into Pantheon, which then analyses the species, attaching associated habitats and resources, conservation status and other codings against them. This information can then be used to assign quality to sites, assist in management decisions and augment other ecological study.
3. Can the "About" box and the "Register" box be equal width?
4. The "Latest samples" is removed and a new "Disclaimer" box added with the statement: It is essential that you read the disclaimer before using Pantheon.
5. The statement about the steering group can be discarded.

**Comment by HDean** [comment]
Sorry, can you also add under the disclaimer sentence:

Pantheon does not cover:
•	the fully marine environment, although though it does cover lagoons, brackish water and saltmarsh, or
•	all UK species, and will have limited application to near continental Europe.

**Comment by johnvanbreda** [comment]
All done
