### ISSUE TITLE
Font size different on results overview from the scratchpad

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#155]
When running the analyses from a list saved on the scratchpad, the results overview headings have a different font size - the "Basic output" heading is smaller than the "Scratchpad overview" and the "Taxonomic output"

**Comment by johnvanbreda** [comment]
Actually the problem was that Basic Output was an unnecessary sub-heading, inconsistent with the sample results output, so I've removed it. I've also made the headings consistent (Scratchpad overview is now Species list overview).
