### ISSUE TITLE
IEC score calculating incorrectly?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#156]
I've just run a scratchpad list through that according to the species list table only has two species with an IEC score, both of which score 1 in both the old and the new IEC. But on the habitat scores report the sample has been given an old IEC and new IEC of 7. See:
http://www.brc.ac.uk/pantheon/horus/quality-scores-overview?dynamic-sample_id=62&dynamic-sample_type=scratchpad

**Comment by HDean** [comment]
@johnvanbreda, another high priority one.
Allan Drewitt at NE has confirmed that the IEC and RIEC is a simple sum of scores for the sample that should be reported. So in Martin's example above, if there are two species each with a score of 1, then the IEC score would be 2.

**Comment by johnvanbreda** [comment]
Fixed and will be deployed with next code release.
