### ISSUE TITLE
Adult and larval feeding guilds are reversed

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#157]
For many, probably all, species, the data given for adult feeding guild and larval feeding guild is reversed (or perhaps the column headings have got reversed), so that e.g. adult butterflies are shown as herbivores and caterpillars as nectivores.

I'm sure this was the right way round last time I looked!

**Comment by HDean** [comment]
I've checked and it does appear that larval guild and adult guild headings have got switched around.
@johnvanbreda is this easy to update?

**Comment by johnvanbreda** [comment]
I've fixed this. I'm not sure what happened - the import scripts look correct.
