### ISSUE TITLE
Text re: different dates and grid refs when importing data from a csv file

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#158]
When data are added by uploading a CSV file, there needs to be some explicit text with regards to multiple dates and multiple grid refs. Something explaining that lists containing more than one date will split the list into multiple samples rather than one single one using the date or grid ref or combination of the two for the samples.

**Comment by HDean** [comment]
David H's suggestion (although he did suggest that this goes on the front page)

To develop a sample for a site that reflects the true output value of Pantheon, users should apply a single grid reference and date for all taxa that they wish to include. Failure to apply this rule will result in each entry being viewed as a sample.

**Comment by HDean** [comment]
Hi @johnvanbreda 
Another one that was not on the original work schedule but if it is quick and easy to do, then it would be great if this could be added. We are still getting a lot of single species samples. David's text above is good but I would perhaps amend it to:

Please use a single grid reference and date for all taxa you wish to include in your sample. Failure to apply this rule will result in each entry being viewed as a separate sample.

Or something similar! Not strictly true but it gets the point across!

**Comment by kitenetter** [comment]
This process would be helped if we could make it possible (and easy) to add date ranges rather than single dates. Personally I think we should steer people as firmly as possible to using the paste option, rather than uploading, unless they have a real need to upload multiple samples at once.

**Comment by johnvanbreda** [comment]
Could we insert a new instructions page which the menu link takes you to, then at the bottom of the instructions page we could add a button that takes you to the current upload tool?

**Comment by HDean** [comment]
Hi John,
Yes we could do that - I think this does need to be done fairly quickly as there have been a lot of single species added recently. Is it possible for you to set up the page with button and I can then edit the text?

**Comment by johnvanbreda** [comment]
The page is here: http://www.brc.ac.uk/pantheon/import-instructions. Once you've added the instructions I'll swap the menu item over.

**Comment by HDean** [comment]
Hi John,
I have now updated this page - can you please swap over the menu item.

**Comment by johnvanbreda** [comment]
Done
