### ISSUE TITLE
CSV download options inconsistent

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#159]
We have ended up with CSV download options in several places, a bit inconsistently and without any option for downloading Assocations as far as I can see.

The current situation is:
- Species list page: no download link
- Ecological guilds page: download available
- Habitats and resources - tabular: download available
- Associations: no download link
- Combined summary page: provides download links for all tables except the Associations table

I'm 99% certain I have downloaded Associations in the past.

**Comment by HDean** [comment]
Species list page - download is now available.
Associations - no download

**Comment by HDean** [comment]
Closing this as the only outstanding one, the associations has its own issue. #118
