### ISSUE TITLE
User stats for Pantheon

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#160]
Jim's initial thoughts as to how these might be tackled and a rough idea of time :

•	Number of visitors: Google Analytics – an hour (if not already in place)
•	Number of new accounts: Drupal view – an hour (Assuming you mean Drupal accounts – be aware of spam accounts.)
•	How long they stay: Google Analytics up to a point (http://help.analyticsedge.com/googleanalytics/misunderstood-metrics-time-on-page-session-duration/)
•	How many samples loaded: Indicia report – an hour or two
•	How many species loaded: Indicia report
•	How many downloads from the analyses – Google Analytics possibly (https://support.google.com/analytics/answer/1012044?hl=en) 
•	What area does the user work in – Drupal User profile plus Drupal View – an hour (but may only gather information about new users)
•	What Pantheon is being used for – Is this an extension of the previous point?

It is also possible to introduce questionnaires rather than using the Drupal User Profile to gather information. (https://www.youtube.com/watch?v=qqYX-ZV5ezc) Not sure if that offers any particular advantage here.

Looks like pretty easy requirements at first glance although that is a pretty superficial estimate.

**Comment by HDean** [comment]
Hi @johnvanbreda 
Can you provide some really brief stats on Pantheon for Jon W? We are after how many users are registered to use Pantheon, how many lists have been loaded. Any easy stats like that would be appreciated.
Thanks, Hannah

**Comment by johnvanbreda** [comment]
Total registered users 467
Total users who have added a list or uploaded a sample 148
Published records 70399
Published samples 12623
Pasted species entries 191401
Pasted lists 750

In case it's useful, here's the query:
```
select 1 as sequence, 'Total registered users', count(distinct uw.user_id) 
from users_websites uw where uw.website_id=93
union
select 2, 'Total users who have added a list or uploaded a sample', count(distinct uw.user_id) 
from users_websites uw 
left join cache_occurrences_functional o on o.created_by_id=uw.user_id and o.website_id=93
left join scratchpad_lists sl on sl.created_by_id=uw.user_id and sl.website_id=93
where uw.website_id=93 and (sl.id is not null or o.id is not null)
union
select 3, 'Published records', count(*) as value from cache_occurrences_functional where website_id=93
union
select 4, 'Published samples', count(distinct sample_id) as records from cache_occurrences_functional where website_id=93
union
select 5, 'Pasted species entries', count(sle.*) from scratchpad_list_entries sle
join scratchpad_lists sl on sl.id=sle.scratchpad_list_id and sl.deleted=false
where sl.website_id=93
union
select 6, 'Pasted lists', count(*) from scratchpad_lists sl where sl.deleted=false and sl.website_id=93
order by sequence
```

**Comment by HDean** [comment]
Brilliant, thank you!
Closing this for now - may revisit the stats requirements in a year's time
