### ISSUE TITLE
Species Designation "hover-over"

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/Pantheon#17]
Provide hover-text to Species Designation information as follows:

LABEL: HabRegs2. The Conservation (Natural Habitats, &c.) Regulations 2010 (Schedule 2), European protected species of animals.
LABEL: WCA5/9.4c Wildlife and Countryside Act 1981 (Schedule 5), Animals which are protected from their access to any structure or place which they use for shelter or protection being obstructed.
LABEL: Sect.41. Natural Environment and Rural Communities Act 2006 - Species of Principal Importance in England. Species of principal importance for the purpose of conserving biodiversity covered under section 41 (England) of the NERC Act (2006) and therefore need to be taken into consideration by a public body when performing any of its functions with a view to conserving biodiversity. . 
LABEL: NR. Nationally Rare. Occurring in 15 or fewer hectads in Great Britain
LABEL NS: Nationally Scarce. Occuring in 16-100 hecatads in Great Britain
LABEL VU: IUCN Vulnerable
LABEL CR: IUCN Critically Endangered
LABEL EN : IUCN Endangered
LABEL pVU: Provisional IUCN Vulnerable
LABEL pCR: Provisional IUCN Critically Endangered
LABEL NT: IUCN Near Threatened
LABEL LC: IUCN Least Concern
LABEL pEN: Provisional IUCN Endangered
LABEL pNT: Provisional IUCN Near Threatened

**Comment by HDean** [comment]
New Species Designation data is going to be provided by Jon Webb and Mark Gurney. Not all of the above labels may be required.

**Comment by johnvanbreda** [comment]
This requirement might be replaced by using the Lexicon to show popup/hover information for all labels in all the reports (where possible).

**Comment by johnvanbreda** [comment]
Closing this because the Lexicon should be used to set up the hover over.
