### ISSUE TITLE
Link names on the Traits page to the glossary 

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#170]
The list of traits at:
http://www.brc.ac.uk/pantheon/explore/traits

needs to be linked to the glossary

**Comment by HDean** [comment]
Hi John,
I thought I might be able to do this but I can't edit the items in the table. This is not urgent at all.
Basically, can the title of the trait (e.g. coastal) hyperlink to the term "coastal" in the glossary?

**Comment by johnvanbreda** [comment]
I managed to automate this. For future reference, I added the following to the header of the view:

```
<?php
iform_load_helpers(array('report_helper'));
$path = dirname($_SERVER['SCRIPT_FILENAME']) . '/' . report_helper::relative_client_helper_path();
require_once $path . '/prebuilt_forms/extensions/pantheon.php';
drupal_add_js($path . '/prebuilt_forms/extensions/pantheon.js');
extension_pantheon::lexicon(null, null, null, null, null);
handle_resources();
?>
```
