### ISSUE TITLE
Add download of species index

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#172]
JvB's comment: Suggest we download the file each time a db update is done, then upload the file so that different versions are kept with an easy link to the latest. This will mean no need to query the server every time it is downloaded

**Comment by johnvanbreda** [comment]
Next warehouse update will provide:
1) A cached table containing the species index, so it will load much faster.
2) I can then set up a page allowing you to grab the download file any time you want to recreate it, plus I'll save the current output into a file and provide a link.

**Comment by johnvanbreda** [comment]
Ok, there is now a Species Index download page available to administrators only. This has a version of the grid without the lexicon <span> formatting and it also has a download link on the page which gives you a full copy of the dataset. This page is only needed when refreshing the stored copy of the index.
To refresh the index file copy, download the csv file and rename it to species-index.csv, then zip it. The file needs to go on wlbrcweb1, in D:\web sites\drupal7\sites\www.brc.ac.uk.pantheon\files. 

The file can now be downloaded via a link at the top of the normal species index page.
