### ISSUE TITLE
Potential to "double-count" as a result of 1 to many mapping

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#174]
David Heaver's comment:

Careful use of the headers to distinguish those instances of a report showing number of species hits against those other instances where it is a summation of the number of unique species.

If not carefully handled, some entries can be read as the number of unique species attached to an attribute, whereas in fact the same species can pop up elsewhere in the other attributes counts. A subtle point but it is important for the user to be aware when looking at species status summation for, say, Molinia, and them not recognising that a taxon also occurs on Festuca rubra and that its conservation status score carries across to that plant as well, i.e. in that instance there are not 2 taxa as, say, VU, but one.

**Comment by HDean** [comment]
I think what is meant by the above comment is that someone less well acquainted with traits data might think that the number of species provided against one trait is a count of a list of species that is totally different from the list of species provided against a different trait.

i.e. Trait 1 has 2 species - species x and species y
Trait 2 has 1 species - species z

whereas in reality Trait 2 could have species x against it.

**Comment by HDean** [comment]
From discussions with Jon W, what David is meaning is that it would ideal if in the number of species, it could be flagged how may of those species are only found in that particular habitat/resource.
e.g. within brackish dune slacks there are 20 species of which 5 are specialists.
So the 5 specialist species are only found with brackish dune slacks and in any other of the coastal resources.

**Comment by johnvanbreda** [comment]
@hdean Can I just ask for a definitive list of places where you want to show the number of specialists please? Examples I can think of:
Habitats & resources > hierarchy
Habitats and resources > tabular > No. of species column (4 tabs)
Habitats and resources > tabular (other) > No. of species column (3 tabs)

I.e. does this also need to apply to feeding guilds no. of species column, or any of the scores on habitat scores?

**Comment by HDean** [comment]
Hi @johnvanbreda 
Put this one on hold for now. It needs further discussions with Jon and David as to what is actually meant by this and what they want to see. As it doesn't affect how Pantheon works then I think we leave this to nearer the end and if we have time left, then we can try and sort it.

**Comment by HDean** [comment]
Closing this as it is not going forward within the next year or so.
