### ISSUE TITLE
List of species for SAT is not correct

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#175]
One tester found that when clicking on the number of species reported against a SAT, it produced a list of species that did not tally with the number reported.

Example: sample ID 259 (on scratchpad) shows 4 species for SAT F002. When the "4" is clicked, it provides a list of 10 species.

**Comment by HDean** [comment]
Having looked into this further, the number of species being reported is incorrect. The list of species is correct. But there are also other issues - the SAT report isn't displaying properly.

In the image below, there are four highlighted entries - these are 2 duplicates. One duplicate matches on the number of species (undisturbed fluctuating marsh), the other duplicate doesn't (heartwood decay)! And the way the duplicate records are being displaying differs when the hierarchy should be the same in both cases (one record shows the habitat in the habitat column, the other record shows the habitat in the SAT column as well as the SAT).

![image](https://user-images.githubusercontent.com/17744201/30474417-883ab950-99fb-11e7-8b06-ba5a44b45b55.png)

**Comment by HDean** [comment]
Hi @johnvanbreda 
Again not on the work schedule but is an important one to fix. David H has also highlighted the same issue to me this morning.
His feedback:
Species list for sample: sample ID 453
It reports 3 F003 taxa under Habitats & resources: ISIS specific assemblage types
but when the “3” is expanded they reveal 4 taxa underneath.

**Comment by johnvanbreda** [comment]
I agree, there are a few things wrong here. I've written a simpler query than the report actually in use to show the SAT output for scratchpad 259, limiting it to the F002 (rich flower resource) SAT:
```
-- Query to load the SAT output for scratchpad 259/F002
select 
  t_bb.id as bb_term_id, 
  t_sb.id as sb_term_id, 
  t_sat.id as sat_term_id,  
  t_bb.term as bb_term,
  t_sb.term as sb_term,  
  p.term as parent_sat,  
  t_sat.term, 
  count(distinct cttl.preferred_taxa_taxon_list_id) as species_count
-- Start by pulling in the list of SAT terms
from taxa_taxon_list_attribute_values av_sat
join cache_termlists_terms t_sat on t_sat.id=av_sat.int_value
-- Join via the species data linked to the SAT term to the appropriate scratchpad list
join cache_taxa_taxon_lists cttl on cttl.preferred_taxa_taxon_list_id=av_sat.taxa_taxon_list_id
join scratchpad_list_entries sle on sle.entry_id=cttl.id
              and sle.scratchpad_list_id=259
-- Include the specific biotopes
left join taxa_taxon_list_attribute_values av_sb on av_sb.taxa_taxon_list_id=cttl.preferred_taxa_taxon_list_id and av_sb.deleted=false
        and av_sb.taxa_taxon_list_attribute_id=16
left join cache_termlists_terms t_sb on t_sb.id=av_sb.int_value
left join taxa_taxon_list_attribute_values av_bb on av_bb.taxa_taxon_list_id=cttl.preferred_taxa_taxon_list_id and av_bb.deleted=false
        and av_bb.taxa_taxon_list_attribute_id=15
left join cache_termlists_terms t_bb on t_bb.id=av_bb.int_value
-- This includes a SAT parent term, if a child of the row's SB (or BB is SB blank), but not if it is the SB or BB itself. I.e. include
-- the parent of the SAT term if it is a new additional level not otherwise included in the data.
left join cache_termlists_terms p on p.id=t_sat.parent_id 
  and p.parent_id=coalesce(t_sb.id, t_bb.id)
  and p.id not in (t_sb.id, t_bb.id)
where av_sat.taxa_taxon_list_attribute_id=20
and av_sat.deleted=false
and t_sat.id=9898 -- F002
group by t_bb.id, t_sb.id, t_bb.term, t_sb.term, p.term, t_sat.id, t_sat.term
```

The output is:
```
10268;10066;9898;"open habitats";"decaying wood";"";"rich flower resource";3
10268;10270;9898;"open habitats";"tall sward & scrub";"";"rich flower resource";8
10268;10272;9898;"open habitats";"short sward & bare ground";"";"rich flower resource";13
10268;;9898;"open habitats";"";"";"rich flower resource";1
10512;10066;9898;"tree-associated";"decaying wood";"";"rich flower resource";3
```

I think this is correct but would appreciate it if you could check it. It appears to show 28 species but I think 3 are overlaps between the different hierarchies. 

If I fix the query as above, the 2nd thing that will need fixing is when you click on one of the species count numbers, the filter will need to not just show F002, but F002 within the specific hierarchical context (e.g. rich flower resource within the open habitats > decaying wood branch). Does that sound correct?

**Comment by HDean** [comment]
Hi @johnvanbreda ,
I can't access sample ID 259 - I think the example I gave above was for a different public example - I honestly can't remember but if it is the scratchpad sample then I also can't remember how I got to it!
Your query above about clicking on the F002 - it's logical and would be what I would expect it to do. But I will need to check with Jon W.

**Comment by johnvanbreda** [comment]
It is a scratchpad - I tend to analyze one of my own links then edit the URL to change the ID. Here's a link:
http://www.brc.ac.uk/pantheon/pantheon/summary?dynamic-sample_id=259&dynamic-sample_type=scratchpad

**Comment by HDean** [comment]
I think I am a little confused with this! From looking at the hierarchy diagrams, F002 rich flower source should only come under "open habitats" and is not linked via "short sward & bare ground" or "tall sward & scrub". It is not linked to "decaying wood" in the tree-associated biotope or in the open habitat biotope - actually, I can't see that decaying wood should be linked to Open habitat!
I need to check the database to make sure!

**Comment by johnvanbreda** [comment]
Ok - don't worry - it might be my query logic. I'll look into it and get back to you if I think the data are definitely incorrect.

**Comment by johnvanbreda** [comment]
The new query wasn't following up the hierarchy properly. Here's a new version:
```
-- Query to load the SAT output for scratchpad 259/F002
select 
  t_bb.id as bb_term_id, 
  t_sb.id as sb_term_id, 
  t_sat.id as sat_term_id,  
  t_bb.term as bb_term,
  t_sb.term as sb_term,  
  case when t_satp.id in (t_sb.id, t_bb.id) then null else t_satp.term end as unlinked_parent_term,  
  t_sat.term, 
  count(distinct cttl.preferred_taxa_taxon_list_id) as species_count
-- Start by pulling in the list of SAT terms
from taxa_taxon_list_attribute_values av_sat
join cache_termlists_terms t_sat on t_sat.id=av_sat.int_value
-- Join via the species data linked to the SAT term to the appropriate scratchpad list
join cache_taxa_taxon_lists cttl on cttl.preferred_taxa_taxon_list_id=av_sat.taxa_taxon_list_id
join scratchpad_list_entries sle on sle.entry_id=cttl.id
              and sle.scratchpad_list_id=259

-- This includes a SAT parent term but it will only be included in the output if it is not already set as the broad or specific biotope.
left join cache_termlists_terms t_satp on t_satp.id=t_sat.parent_id 
              
-- Include the specific biotopes
left join taxa_taxon_list_attribute_values av_sb on av_sb.taxa_taxon_list_id=cttl.preferred_taxa_taxon_list_id and av_sb.deleted=false
        and av_sb.taxa_taxon_list_attribute_id=16
left join cache_termlists_terms t_sb on t_sb.id=av_sb.int_value and t_sb.id in (t_sat.parent_id, t_satp.parent_id)

-- include the broad biotopes
left join taxa_taxon_list_attribute_values av_bb on av_bb.taxa_taxon_list_id=cttl.preferred_taxa_taxon_list_id and av_bb.deleted=false
        and av_bb.taxa_taxon_list_attribute_id=15
left join cache_termlists_terms t_bb on t_bb.id=av_bb.int_value and t_bb.id in (t_sat.parent_id, t_satp.parent_id, t_sb.parent_id)
where av_sat.taxa_taxon_list_attribute_id=20
and av_sat.deleted=false
and t_sat.id=9898 -- F002
group by t_bb.id, t_sb.id, t_bb.term, t_sb.term, case when t_satp.id in (t_sb.id, t_bb.id) then null else t_satp.term end, t_sat.id, t_sat.term
```

The revised output is:
```
10268;;9898;"open habitats";"";"";"rich flower resource";25
;;9898;"";"";"open habitats";"rich flower resource";3
```
There appear to be 3 species which are under rich flower resource but NOT under open habitats for the broad biotope. Is this correct?

Here's the full output for this list, without the F002 filter:
```
10268;;9898;"open habitats";"";"";"rich flower resource";25
10512;10066;9890;"tree-associated";"decaying wood";"";"bark & sapwood decay";12
10268;;9896;"open habitats";"";"";"scrub edge";11
10268;;9900;"open habitats";"";"";"scrub-heath & moorland";11
10268;10272;9904;"open habitats";"short sward & bare ground";"";"open short sward";6
;10066;9890;"";"decaying wood";"";"bark & sapwood decay";5
10268;10272;9902;"open habitats";"short sward & bare ground";"";"bare sand & chalk";4
;;9898;"";"";"open habitats";"rich flower resource";3
;;9896;"";"";"open habitats";"scrub edge";3
10460;10462;9908;"coastal";"saltmarsh";"";"saltmarsh & transitional brackish marsh";1
10158;10168;9932;"wetland";"peatland";"";"reed-fen & pools";1
10158;10166;9924;"wetland";"marshland";"";"undisturbed fluctuating marsh";1
10512;10066;9888;"tree-associated";"decaying wood";"";"heartwood decay";1
```

**Comment by HDean** [comment]
I agree that there are 25 species which are in open habitats >> rich flower resource.
I am not sure where the 3 under rich flower resource NOT under open habitats comes from. Rich flower resource should always be under open habitats. It looks to me that there are three species which are open habitats >> rich flower resource and also belong to SAT A212 in decaying wood - is the system somehow counting these?

**Comment by HDean** [comment]
Hi John,
I checked out the sample and this what I think should be reported for the SATs:
A211 Heartwood decay = 1
A212 bark & sapwood decay  = 12
F001 scrub edge = 11
F002 rich flower resource = 25
F003 scrub heath & moorland = 11
F111 bare sand & chalk = 4
F112 open short sward = 6
M314 saltmarsh & transitional brackish marsh = 1
W221 undisturbed fluctuating marsh = 1
W314 reed-fen & pools = 1
Generally it agrees with your output above with the exception of duplicated SATs: rich flower resource, scrub edge and bark & sapwood decay. These all appear to be have species where there is more than one SAT.  For example, there are 5 species which have A212 and at least one other SAT.

**Comment by johnvanbreda** [comment]
I've changed the query and managed to get an exact match to your results. Here's the new query:
```
-- Query to load the SAT output for scratchpad 259/F002
select 
  t_satcode.term as code, 
  t_bb.term as bb_term,
  t_sb.term as sb_term,  
  t_sat.term as sat, 
  count(distinct cttl.preferred_taxa_taxon_list_id) as species_count
-- Start by pulling in the list of SAT terms
from taxa_taxon_list_attribute_values av_sat
join cache_termlists_terms t_sat on t_sat.id=av_sat.int_value
join cache_termlists_terms t_satcode on t_satcode.meaning_id=t_sat.meaning_id and t_satcode.preferred=false

-- Join via the species data linked to the SAT term to the appropriate scratchpad list
join cache_taxa_taxon_lists cttl on cttl.preferred_taxa_taxon_list_id=av_sat.taxa_taxon_list_id
join scratchpad_list_entries sle on sle.entry_id=cttl.id
              and sle.scratchpad_list_id=259

-- This includes a SAT parent term but it will only be included in the output if it is not already set as the broad or specific biotope.
--left join cache_termlists_terms t_satp on t_satp.id=t_sat.parent_id 
              
-- Include the specific biotopes
left join (taxa_taxon_list_attribute_values av_sb
  join cache_termlists_terms t_sb on t_sb.id=av_sb.int_value 
) on av_sb.taxa_taxon_list_id=cttl.preferred_taxa_taxon_list_id and av_sb.deleted=false
        and av_sb.taxa_taxon_list_attribute_id=16
	and (t_sb.id in (t_sat.parent_id) or t_sb.id is null)

-- include the broad biotopes
left join (taxa_taxon_list_attribute_values av_bb
  join cache_termlists_terms t_bb on t_bb.id=av_bb.int_value
) on av_bb.taxa_taxon_list_id=cttl.preferred_taxa_taxon_list_id and av_bb.deleted=false
        and av_bb.taxa_taxon_list_attribute_id=15
	and (t_bb.id in (t_sat.parent_id, t_sb.parent_id) or t_bb.id is null)
where av_sat.taxa_taxon_list_attribute_id=20
and av_sat.deleted=false
--and t_sat.id=9898 -- F002

group by t_satcode.term, t_bb.term, t_sb.term, t_sat.id, t_sat.term
```

The problem stemmed from some code in the original query which allowed for their to be 2 levels of SAT, so a SAT can be a sub-SAT of another SAT. Is this actually the case - can SATs be nested?

**Comment by HDean** [comment]
No, the SATs are not nested within a SAT. Most SATs are equivalent to the resource level but there are three SATs (F001, F002 and F003) that are at the habitat level (with the open habitat series).

**Comment by HDean** [comment]
SATs only appear once in the hierarchy so each one should not appear more than once in a report.

**Comment by johnvanbreda** [comment]
Fixed in code, will be deployed next time server is updated.
