### ISSUE TITLE
Conservation status totals not calculating correctly

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#176]
From Adrian Knowles

![image](https://user-images.githubusercontent.com/17744201/30594820-4d558988-9d47-11e7-844b-4b5b9bf5f157.png)

In the top row it says there are 25 species with conservation status, but the breakdown of species you get from clicking the hyperlink associated with the entry in the conservation status column has 26 species!!

I’ve done a check and it is not counting one of the Nb species – there’s five not 4.  In case it helps, those five are:
Reptalus (Reptalus) panzeri
Tanymecus palliatus
Bombus (Psithyrus) rupestris
Lasioglossum (Evylaeus) malachurum
Lasioglossum (Evylaeus) puncticolle

**Comment by HDean** [comment]
Hi John,
Another high priority one I missed!

**Comment by johnvanbreda** [comment]
Fixed in code, will be deployed next time the warehouse is updated.
