### ISSUE TITLE
Species matching - not matched or matched

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#178]
When pasting a list of species into the scratchpad, a green tick shows that a species is matched. Red text shows there is no match, But some species show in black text and do not show up as matched or unmatched. They have data in Pantheon, so are they included in the reports or not.

This query came from Stuart Connop:
ii) What does it mean when you get black text (see image below) i.e. no green tick, no red tick and no options to choose between non-unique matches? For example for my list, after queries, the result was: Total 1018; Matched: 961; Queried: 0; Unmatched: 3 - so 54 species were neither matched nor unmatched.

![sc](https://user-images.githubusercontent.com/17744201/31708682-a255a966-b3e7-11e7-879b-779aef31bf4a.png)

**Comment by HDean** [comment]
Hi @johnvanbreda 
Can you have a look at my comment above and let me know what the species in black (i.e. not showing as matched or unmatched) means? Are they included in the analyses?

**Comment by johnvanbreda** [comment]
Hmm, these species do seem to match if I type them in. My suspicion is that there are funny characters in the pasted data which we cannot see that are preventing them parsing. If you paste the list into Notepad first, then copy it again from Notepad into Pantheon, does this still happen? Are you able to send me the text of a list that will allow me to reproduce it?

**Comment by HDean** [comment]
I've requested the list in the original document from Stu Connop.

**Comment by HDean** [comment]
Species list attached - please note the data need to remain private as this is confidential data.
[Data_for_input.xlsx](https://github.com/BiologicalRecordsCentre/Pantheon/files/1449938/Data_for_input.xlsx)

**Comment by HDean** [comment]
This appears to be a list length issue.
I tried pasting the list in and couldn't get it finish checking names even when left for half an hour. Stuart managed to get the list to check correctly by pasting in and checking smaller sections one after the other. Not ideal.
@johnvanbreda is it possible to check if there is an issue with size of pasted list?

**Comment by johnvanbreda** [comment]
I've just tried pasting this list in (data_for_input.xlsx) and it worked - it took 16 seconds, response was Total: 1018
Matched: 940
Queried: 75
Unmatched: 3.
Which browser are you using?

**Comment by HDean** [comment]
Hi @johnvanbreda 
Just checked it again and it now works! I am using Chrome 63.0.3239.84 and I now get the same result you do!

**Comment by HDean** [comment]
As this seems to have resolved itself I am closing the issue.
