### ISSUE TITLE
Filter boxes not working for Habitats tabular view

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#182]
When using the tabular view of the biotopes/habitats hierarchy, any attempt to filter the data using the text box above each column results in:

![image](https://user-images.githubusercontent.com/16039111/32465519-a47ce2d2-c33b-11e7-8045-2222a477f567.png)

**Comment by johnvanbreda** [comment]
Fixed and will be deployed next time the warehouse is updated.
