### ISSUE TITLE
Inflorescence terminology/definition unclear

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#183]
Need to clarify the difference between “inflorescence” and “nectar and/or pollen” (the former seems to include the latter according to the glossary):

![image](https://user-images.githubusercontent.com/16039111/32465610-fcc73d84-c33b-11e7-9c5f-8e7543a6fdf9.png)

**Comment by HDean** [comment]
Requesting definitions from Jon W.

**Comment by HDean** [comment]
Definitions provided by Jon and updated in/added to the glossary.
