### ISSUE TITLE
"variable" terms are unhelpful?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#184]
Some resources are labelled as variable, e.g. “soil humidity >> variable humidity” – is this really informative? Does it imply that species actually _depend_ on the variability? If not does it say anything meaningful?

**Comment by HDean** [comment]
Requesting a decision from Jon W on whether we remove or change this.

**Comment by HDean** [comment]
Possibly remove in future but there are too many typed to the variable traits to remove at present (requires going back through the hierarchy).
