### ISSUE TITLE
Navigation of the "my-list" page not correct

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#187]
Paste species list page (http://www.brc.ac.uk/pantheon/species-lists/my-list) displays the total number of lists incorrectly, and if you click through to a page that is beyond the end of your actual lists you lose the ability to navigate back to the first page:

![image](https://user-images.githubusercontent.com/16039111/32466371-a9db1782-c33e-11e7-8a2c-bb07d2460940.png)

**Comment by johnvanbreda** [comment]
Fix will be deployed next time warehouse updated.
