### ISSUE TITLE
Order counts/percentages in reports in descending order

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#19]

**Comment by johnvanbreda** [comment]
This affects the default sort order of existing reports, e.g. guild output, taxonomic output, which should by descending species count unless otherwise specified.

**Comment by johnvanbreda** [comment]
The 2 tables on the first summary page are done. @HDean does this need to apply to the species index and species lists produced within an analysis as well?

**Comment by johnvanbreda** [comment]
I've also sorted tables on the combined summary.

**Comment by HDean** [comment]
Hi @johnvanbreda,
The sort should be done on any analysis output where there is a percentage/count.

**Comment by johnvanbreda** [comment]
Hopefully all covered that are relevant now. The Osiris tabular form can't really be sorted this way in the default output form which is hierarchically structured.
