### ISSUE TITLE
Wording and signposting for pasting species lists needs review

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#192]
Users find it hard to learn how to navigate the paste lists options. Issues:
1. Clarify the differences between "Add data - Paste species list" and the other Add data options
2. From http://www.brc.ac.uk/pantheon/species-lists/my-list : Make a clearer distinction between the "Paste new species list" link and the table of previously pasted lists - maybe put the "Paste new species list" link above the "My species lists" heading? Or see point 7 below.
3. Change the "My species lists" heading to "Species lists previously pasted in"?
4. Make it possible to delete a previously pasted list (already in #147 )
5. Drop the term scratchpad, which doesn't relate to the menus
6. Maybe use "Save to my Pantheon" for the initial save of a pasted list, and then use "Save to public database" for what we currently call "Add metadata"?
7. Make it easier for people to refind their previously pasted lists - it is not intuitive that you have to go back to paste a new list in order to see the existing ones. Maybe the link under the "Add data" menu should go straight to http://www.brc.ac.uk/pantheon/species-lists/edit and then we add a link under "Explore" (called "My pasted lists"???) that goes to http://www.brc.ac.uk/pantheon/species-lists/my-list

Once you have decided to "Add metadata", the form that opens up is not ideal:
1. The date box really needs to be able to cope with a date range - people often upload lists that have been collated over months or years, and at the moment they are forced to assign a single date. Probably easiest to provide separate "Date from" and "Date to" fields?
2. I don't see much need for adding a comment against a species, and I see no need at all for adding a photo at this point
3. Last year we had some discussion (#131) over what other information would be useful to store here, such as some measure of sampling effort - worth returning to that discussion if we are able to develop the metadata aspect further

**Comment by HDean** [comment]
I think most of this has been covered:
The link/menu name has been changed.
List can be combined or deleted.
There is now info on how to add records when a user logs in.
Metadata has been updated to include sampling 
Closing issue.
