### ISSUE TITLE
Enhancement: add a vernacular name column to the species tables

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#193]
Some users have requested the addition of a vernacular name column to the species tables - I think this would be a useful option to add to the columns available to these tables.

**Comment by johnvanbreda** [comment]
This is simple for me to implement - over to @hdean for consideration.

**Comment by HDean** [comment]
@johnvanbreda @kitenetter I have a meeting with Jon W tomorrow so I will put this on our discussion list.

**Comment by johnvanbreda** [comment]
Done
