### ISSUE TITLE
Further feedback on typing and data

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#195]
Diptera
Cheilosia soror
Should not be listed as upland; also not sure what Tuber refers to as an association (it is believed to be associated with truffle fungi I believe, but I’d need to check that)

Hemiptera
Deraocoris ruber
Is listed as a herbivore but association is given as “Arthropoda”
HD  comment - association doesn't have to be as food - it might be associated in another way.

Lepidoptera
Diachrysia chryson
Primary association is with wetland, including open wet woodland, seems misleading to type it as tree-associated, and incorrect to type it to heavy shade.

Rhizedra lutosa 
Should be “Section 41 Priority Species - research only”
HD comment - it is but isn't showing up in the species index.

Orgyia recens
Should be RDB2 and Section 41 Priority
HD comment - it is but isn't showing up in the species index.

Unknown category
Unclear how this is being used, e.g. why are these two Platycheirus flagged as unknown?:
HD comment - Unknown is a category under "habitats" which is a second level trait in the "open" biotope hierarchy.

**Comment by kitenetter** [comment]
Re Deraocoris ruber, as far as I know it is a predator of other small insects especially aphids, so the association is correct but it is wrong to list it as a herbivore. "Larvae and adults feed on small insects, especially aphids; they are found on many plants and bushes, particularly nettles." (Southwood and Leston 1959.)

**Comment by HDean** [comment]
Feedback on typing to be done as reviews at a later date.
