### ISSUE TITLE
'Long' pasted species lists not being accepted?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#197]
Craig Macadam reports pasting in a list of 540 species, clicking the "Check" button, and the system then just displays a timer and never finishes the checking. I've pasted in the same list to my account and get the same result. 

Craig has been able to paste the species in if he does it as two shorter lists, but there shouldn't be a limit to the number of species should there? I've pasted in up to 1,800 species in the past and not encountered problems.

**Comment by johnvanbreda** [comment]
@kitenetter I suspect a problem specific to the list rather than a timeout caused by a long list. Are you able to supply the list to me please?

**Comment by HDean** [comment]
@johnvanbreda I also had the same problem when looking into #178 . Again we thought the particular problem the user was having might be related to a specific issue with the list. I requested a copy of the list and decided to see if I could replicate the user's problem. But, as above, I couldn't get the system to finish checking the list. I was going to try your suggestion of copying and pasting into Notepad first but haven't had a chance to try it yet.

**Comment by HDean** [comment]
@johnvanbreda just tried copying and pasting the list from #178 into Notepad and then into Pantheon, and it is still checking the species list after 25mins! The list is of 1018 species.

**Comment by johnvanbreda** [comment]
After much investigation we discovered a bug in one of the libraries installed on the server. Biren has installed a different version and it should now work.
For info, see https://github.com/curl/curl/issues/1949.
