### ISSUE TITLE
Request for enhancement: provide SQI for whole list

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#199]
A user has asked whether Pantheon could provide an SQI score for the list as a whole - at the moment we only give SQIs for each entry in the habitat hierarchy, but we don't give an overall SQI for the whole list.

If it is possible to add this, I think it would best be displayed on the "Habitat scores" page, near the top under "Number of species with habitat scores"?

**Comment by Davydaveth** [comment]
A user variant of this.....A few consultancies have commented that Pantheon should report on all taxa found, whether analysed or not. The aim would is to present a complete list of everything caught, with its taxonomy, so as to enable surveyors to integrate the taxonomic catch list easily within their reports, and then move onto looking at the analysis. The output should also list those taxa which are excluded from analysis, clearly labelled. There should be agreement between the table of the number of taxa reported by order in a sample with the hyperlinked link list: currently they can disagree with each other.

**Comment by johnvanbreda** [comment]
Total SQI added to habitat scores report.

@Davydaveth I've left the point about reporting on all taxa found as you can already do a full species list via the link on the overview page, plus it's a different issue to the original post.
