### ISSUE TITLE
Revised Pantheon menu layout

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/Pantheon#2]
Top level menu items:
- Home
- News
- Add data
- Explore samples
- Species Index
- About

Sub-menus.
Add data:
-    Enter full sample data
-    Enter a species list
  # note that both sub-menus will allow entry of new data via an import form, or to paste in data

About:
- Help
- Pantheon Lexicon

**Comment by johnvanbreda** [comment]
Reviewed after meeting:
- Home
- Add data
  - Enter full sample data
  - Import full sample data (CSV import)
  - Enter a species list (=scratchpad to paste into)
- Explore samples
- Explore species (an unfiltered version of the species list page for all Pantheon sp.)
- Help
  - About
  - Pantheon Lexicon

We will use Drupal content types to capture the glossary of terms in the Lexicon in a structured form and auto generate the output using views. This will ensure consistency and also facilitate things like automatic display of popup hints explaining the terms in the reports.

**Comment by HDean** [comment]
This is done. Extra items can be added as required.
