### ISSUE TITLE
Printer friendly outputs, including PDF downloads, for summary tables/results

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#20]

**Comment by HDean** [comment]
Dependent on NE deciding what they would like in the outputs.

**Comment by HDean** [comment]
Download to Excel complete.
PDF still to do.

**Comment by johnvanbreda** [comment]
Will need configuration to add the [print.pdf] control to each page, after the next release is deployed.

**Comment by johnvanbreda** [comment]
I've added the pdf button to the list of links at the bottom of each page. A couple of points:
* I didn't do the species list or combined summary reports - there seems to be a limit to the length of the PDF document which can be generated and a long species list won't work. It is fine for all the summary reports though.
* You may need to experiment with the landscape/portrait format option to get the best results.

Please close this if you are happy with the functionality.

**Comment by HDean** [comment]
Hi @johnvanbreda ,
This looks good - landscape is definitely better.
There are a couple of things I have noticed:
1. the summary statements about the conservation status gets lost in the PDF which reports it as a list of the conservation status. For example: 6 Na shows as Na|Na|Na|Na|Na|Na|
2. when the PDF has been generated you loose the buttons at the bottom of the page, so you have to go back to the home page and start again. Is there anyway to maintain the buttons (Back to summary, species list, etc).

**Comment by johnvanbreda** [comment]
Now done.
