### ISSUE TITLE
Add some more brief details to the "tabular - other" button info

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#201]
At the moment the info next to button "tabular - other" states: View other classifications for this sample as a set of tables. A little bit more text is needed here to make it clearer.

So something like: View other classifications (e.g. dung and carrion, plant-associated traits, synanthropic) for this sample as a set of tables.

**Comment by HDean** [comment]
Hi @johnvanbreda 
Could you make the above amendments to the text? I don't have permission to edit.

**Comment by johnvanbreda** [comment]
Done
