### ISSUE TITLE
Add citation to Pantheon home page

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#204]
The citation for Pantheon is currently on the Acknowledgements page and the About page. The citation should be added to the main Pantheon page, where it currently says Pantheon database version X.X.X. Will need adding after the latest data import.
Could also be added as a separate menu item on the home page. A menu title of "Citation" with a single page that just lists the citation.

**Comment by HDean** [comment]
Hi @johnvanbreda ,
Can you please add this reference to the footer of Pantheon, where it currently just says "Pantheon database version 3.7.4" - you may want to leave it until the data upload is complete. Thanks.

Webb, J., Heaver, D., Lott, D., Dean, H.J., van Breda, J., Curson, J., Harvey, M.C., Gurney, M., Roy, D.B., van Breda, A., Drake, M., Alexander, K.N.A. and Foster, G. (2017). Pantheon - database version 3.7.6

**Comment by johnvanbreda** [comment]
I've done this but left the db version as 3.7.4. When we update the data, should I change the year in the reference?

**Comment by HDean** [comment]
Hi John,
Yes please - totally overlooked that!
