### ISSUE TITLE
Species lists not loading

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#205]
I'm looking at one of my pasted lists:
http://www.brc.ac.uk/pantheon/pantheon/summary?dynamic-sample_id=117&dynamic-sample_type=scratchpad

From the summary page I can open up species lists for each taxonomic group, but the links to species lists from the feeding guild and habitat hierarchy pages generate an error "The report did not load correctly".

**Comment by johnvanbreda** [comment]
Fixed.
