### ISSUE TITLE
"None" showing conservation status column

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#206]
The totals for conservation statuses are correct but when you look at the list of species it shows "none" (these aren't counted in the totals). Can this be removed? If it is a big job, then leave it but if simple to fix then could it be please!
Thanks, Hannah

**Comment by johnvanbreda** [comment]
The pre-populated species index table did not limit the conservation designations shown unlike the other reports. Now fixed.
