### ISSUE TITLE
Add extra menu item to "Explore"

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#207]
Add something like "explore my pasted lists" to the explore menu to allow easier finding of the pasted species lists.

**Comment by johnvanbreda** [comment]
Wouldn't this be the same as the link under Add data > Paste species lists (i.e. to http://www.brc.ac.uk/pantheon/species-lists/my-list)?

**Comment by HDean** [comment]
Yes it would be - most people don't think to look at Add data > Paste species lists to find their previously pasted lists. I thought that adding a link under the Explore menu might help.

**Comment by johnvanbreda** [comment]
Ok - then perhaps the solution is for Add data > Paste species list to go direct to http://www.brc.ac.uk/pantheon/species-lists/edit (where you paste a new list) so the 2 options do something different?

**Comment by HDean** [comment]
Hi John,
Yes, I like that idea. However, hold off on making any changes just yet. I want to check with Jon W that he is happy with that change. Most users now know where to access their pasted lists so moving it might throw them a bit, and Jon may prefer for that not to happen.

**Comment by HDean** [comment]
Hi @johnvanbreda 
Having checked this with Jon W, the plan is NOT to add anything to the Explore menu but to change what it says under the Add data menu. Instead of "Paste species lists", can it be changed to "Paste and analyse species lists"? Thanks.

**Comment by johnvanbreda** [comment]
Done
