### ISSUE TITLE
Possible SQI error with single and combined lists

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#209]
Feedback from a user:
I just tried the quick analysis group on a couple of datasets and found that the SQI values under Habitat & Resources (both tabular and hierarchy) differed between grouped data and the original dataset. Investigating the figures I see that the species with conservation status are identical for each but the SQI calculation is slightly different. 

Screen shots attached. 
![pantheon1](https://user-images.githubusercontent.com/17744201/36318765-be82cc62-1338-11e8-9bca-a5ddf28c6059.JPG)
![pantheon2](https://user-images.githubusercontent.com/17744201/36318766-beb8f828-1338-11e8-9f75-a0a88c958afa.JPG)

**Comment by HDean** [comment]
Hi @johnvanbreda ,
Can you have a look at this? No one else has noticed this problem (yet) but that could mean no one has noticed it! The broad biotope is identical for a single and also the combined the lists but the SQI values differ for the tree-associated and the list in Conservation status differs (there are 5 Nbs in the single list and 6Nbs in the combined list, even thought the species lists are reported as being identical).

**Comment by johnvanbreda** [comment]
I've fixed the issue with SQI (where the calculation was being influenced by duplicates). Still need to check the conservation statuses.

**Comment by johnvanbreda** [comment]
Conservation statuses done
