### ISSUE TITLE
Incorrect rarity status for bee

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#211]
Pantheon lists the solitary bee Hylaeus (Lamdopsis) dilatatus as RDB 3, but that status is incorrect, and should be transferred to Hylaeus (Lamdopsis) annularis.

This originates from a change of name (annularis used to be called dilatatus).

**Comment by kitenetter** [comment]
But this may get corrected when the database is updated! So this could be a false alarm (just happened to find it while using Pantheon for PoMS). Will close for now and check after the update.

**Comment by kitenetter** [comment]
This is still incorrect in Pantheon.

- Hylaeus annularis is currently shown as having no conservation status - it should be RDB3.
- Hylaeus dilatatus is currently shown as RDB3 - it should have no conservation status.

**Comment by AdrianPKnowles** [comment]
STILL uncorrected in September 2021.  I'm going to have to delete this species from the list I'm analysing because it seems to be affecting the SQI calculation (I've done the calculation with and without the species).

It is annoying that this potentially very useful tools still has 'bugs' in it, that many people would just accept unknowingly.

**Comment by kitenetter** [comment]
@AdrianPKnowles thanks for bumping this one again. I will ask David Heaver if we can find a way of sorting it out, but I think he's away for another week or so.

The scores for the two species do seem to be correct (annularis = 8, dilatatus = 1), so I'm not sure why the SQI is being affected, but let's see if we can get the status corrected first.

**Comment by AdrianPKnowles** [comment]
Actually I was wrong about SQI change - it was a tired and frustrated comment! Is it just that the label in UKSI is wrong.?

**Comment by johnvanbreda** [comment]
I've fixed the statuses - please check and close if OK.

**Comment by kitenetter** [comment]
Thanks @johnvanbreda - these two bees are now displaying correctly. Closing.

**Comment by AdrianPKnowles** [comment]
I’ve just come across another – the wasp Pemphredon lethifer is most definitely not RDB 3!!  It has the correct SQS score of 1 in the species list.  This is probably down to synonym problems with P. enslini, that is now deemed to be part of lethifer

 

Adrian
