### ISSUE TITLE
Error in output: dung and carrion double-displayed

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/Pantheon#214]
double-displayed
![image](https://user-images.githubusercontent.com/2699478/38667847-77a0a1d4-3e3a-11e8-82b9-74300290938e.png)

Or in this instance triple display of dung but with different scores and species under each 
![image](https://user-images.githubusercontent.com/2699478/38667862-886d16be-3e3a-11e8-9e68-b0d3d7d8e3a6.png)

**Comment by johnvanbreda** [comment]
This is occurring when dung & carrion appears in several places in the hierarchy, e.g. for the first example, it appears as a top-level term as well as under tall sward. The querying required to aggregate to single terms may be fairly complex so I'd estimate 3 hrs to fix it.
