### ISSUE TITLE
Remove NA (not applicable) from reports including conservation status

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/Pantheon#215]
NA (standing for Not Applicable) counted in Species with a conservation status and Conservation status columns where it shouldn’t be. Na (stands for ‘Notable a’)  should still be in but NA in capitals should be removed from these columns, not being counted as a species with a conservation status.
![image](https://user-images.githubusercontent.com/2699478/38668225-9132d0f8-3e3b-11e8-8818-007ea1560f51.png)

Need advice on whether to update the Indicia database or update the Access database and have a full reload

**Comment by johnvanbreda** [comment]
NA is being excluded but only for red list designations, not GB status. I think an update to the reports to fix this is the simplest way forward - approx 1 hr.
