### ISSUE TITLE
Explore filters - not working or not needed for reports of samples?

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/Pantheon#216]
Review whether explore filters are needed for 'My samples' or 'All samples' explore reports
http://www.brc.ac.uk/pantheon/explore/my-samples
http://www.brc.ac.uk/pantheon/explore/all-samples

**Comment by johnvanbreda** [comment]
I've corrected both pages so that the filter builder now runs in "Samples" mode, hiding the stuff to do with species filtering. However there are still some issues which need a bit of work on the underlying Pantheon report - approx 1 hour.

**Comment by johnvanbreda** [comment]
Report fixed to work with sample filtering.
