### ISSUE TITLE
Using scratchpad species list, unable to edit after checking

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/Pantheon#221]
Steps to replicate:
1. Follow path to paste species list - http://www.brc.ac.uk/pantheon/species-lists/edit
2. Add species list, select check and then save
3. From list of 'my species lists', e.g. http://www.brc.ac.uk/pantheon/species-lists/my-list.  click on 'edit' for a list
4. Next page has 'save' button greyed out.  There is no way to edit the list after it has been checked

**Comment by johnvanbreda** [comment]
After step 4:
5. Make a change to the list, e.g. add a species.
6. Click Check.
7. Save button becomes enabled.
Does that work for you?

**Comment by DavidRoy** [comment]
that works, thanks
