### ISSUE TITLE
"Explore all samples" fails to run

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#223]
If you log on to Pantheon and go to Explore - Explore all samples, the report attempts to run but after a while stops with an error message:

![image](https://user-images.githubusercontent.com/16039111/43844422-93f98ca8-9b21-11e8-888b-171af76f4a1f.png)

**Comment by johnvanbreda** [comment]
This loads after recent tweaks to the report.
