### ISSUE TITLE
ISIS codes required on all ISIS output

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#23]
ISIS assemblage codes to be used whenever an assemblage is being shown.
This may already be the case. Needs checking.

**Comment by HDean** [comment]
ISIS assemblage codes are not included in the hierarchy view.

The ISIS codes in the species table is not the assemblage code but some other code which has not been added to the database. This is the code that Jon wants included within the table.

**Comment by HDean** [comment]
On second reading of my notes, it may be that the ISIS code Jon wants in the species table is the specific assemblage type. This will need confirming with Jon.

**Comment by johnvanbreda** [comment]
I've added the code to the SATs table now available within ISIS: http://www.brc.ac.uk/pantheon/osiris/tabular?dynamic-sample_id=471276.
I think the ISIS SAT code is correct on the new index output - please close this issue if OK.

**Comment by HDean** [comment]
Checked - codes are correct
