### ISSUE TITLE
Conservation status change

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/Pantheon#232]
1. all species that score 0 which should be changed to null
2. P. lethifer should have no status

**Comment by johnvanbreda** [comment]
@DavidRoy 
1. Please can  you clarify this - score 0 on which attribute?
2. Just to confirm, Pemphredon lethifer should have status RDB 3 removed. Presumably this will be done in the source data as well (so it won't be re-introduced after any future update)?

**Comment by DavidRoy** [comment]
1. The attribute that is used to calculate the SQI calculation.  These species are currently being included whereas they should not.  Does that make sense?
2. Yes, the Access database will need to be updated accordingly

**Comment by johnvanbreda** [comment]
I've removed the values for rarity score=0 and rebuilt the species index. The 2nd point will be picked up by #231.
