### ISSUE TITLE
Usage reporting

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/Pantheon#233]
Require the ability to report on Pantheon usage.

July 2017 report:
160 scratchpads containing 46000 entries. 
305 users although only 54 have uploaded either a scratchpad or a sample.

**Comment by johnvanbreda** [comment]
"375288 scratchpad entries"
"557 users registered"
"1266 scratchpads"
"320 users contributed"

Here's the query used to generate this info:
```sql
select count(sl.*) || ' scratchpads' 
from scratchpad_lists sl
where sl.website_id=93
and sl.deleted=false
union
select count(sle.*) || ' scratchpad entries' 
from scratchpad_lists sl 
join scratchpad_list_entries sle on sle.scratchpad_list_id=sl.id
where sl.website_id=93
union
select count(distinct uw.user_id) || ' users registered'
from users_websites uw
where uw.website_id=93
union
select count(distinct uw.user_id) || ' users contributed'
from users_websites uw
left join scratchpad_lists sl on sl.created_by_id=uw.user_id and sl.deleted=false
left join samples s on s.created_by_id=uw.user_id and s.deleted=afalse
where uw.website_id=93
and (sl.id is not null or s.id is not null)
```

@DavidRoy does this need to be shown on a report page so you can regenerate the output as required?

**Comment by DavidRoy** [comment]
I'll close this issue now, and create a new issue (not to be tacked in this current milestone) for a report and page to access.
