### ISSUE TITLE
Add explanatory text to analysis summary page

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/Pantheon#234]
e.g. http://www.brc.ac.uk/pantheon/pantheon/summary?dynamic-sample_id=1540&dynamic-sample_type=scratchpad

Add explanatory text to say that the number of taxa per taxon_group represents the number of species that can be analysed, not the number of taxa in the sample.  In the example below, there are 24 taxa for 'insect - beetle'.  This is the number that can be analysed.  If the link is clicked it returns a list of 26 taxa though.
![p](https://user-images.githubusercontent.com/2699478/48484563-54852c00-e80e-11e8-86be-d2b4c68d03ab.png)

**Comment by johnvanbreda** [comment]
@DavidRoy Should we do this by adding column headers to the list, e.g. Species, Number analysed, % of total? Or would you prefer a note below the list?
Either way, we can make the links show the correct number of analysed species by adding &dynamic-analysed=t to the URL so the 24 link would show 24 species. Shall I change the links to do this?

**Comment by DavidRoy** [comment]
Table headings please.  Yes, and updated links.

**Comment by johnvanbreda** [comment]
Done
