### ISSUE TITLE
Mismatch in group totals

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/Pantheon#235]
This report suggests that there are 5 species with a conservation status associated with the “open habitats” and those five statuses are listed under “conservation status”.  However, if you click on the hyperlink associated with that list of statuses, a sixth species appears, which is a S41 Priority species (Bembidion quadrimaculatum).

![panth](https://user-images.githubusercontent.com/2699478/48547519-be5f0d80-e8c2-11e8-922c-2222f53debd4.jpg)

**Comment by johnvanbreda** [comment]
Bembidion (Bembidion) quadrimaculatum is not S41 priority species in the database but the Pantheon species index is kept in a separate table as a snapshot for performance. So, presumably this designation did exist at some point but has been removed, so refreshing the species index table has fixed this.
