### ISSUE TITLE
spelling error in names

### ISSUE THREAD

**Issue by AdrianPKnowles** [BiologicalRecordsCentre/Pantheon#236]
Entering Bombus muscorum and Bombus ruderarius in a species list throws up the option of recording them in the sub-genus "Thoracombus".  This should be Thoracobombus.  This error may have been inherited via BWARS checklist?

**Comment by johnvanbreda** [comment]
Fixed - all Bombus (Thoracombus) names corrected in our copy of the data. Will take an hour or two to ripple through the various cache tables.
