### ISSUE TITLE
New page for usage statistics

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/Pantheon#237]
follow on from #233 

Add as a report and create a new page for the website: Usage statistics

Under the About menu: About: Usage statistics

**Comment by Davydaveth** [comment]
This could usefully record:
total number of registered users
Total number of publicly-written database samples, where n>5
Total number of non-public "My species list" database samples, where n>5
Combined number of  samples
Number of monthly log-ins, or similar
possibly cumulative number of samples added over time- graphable? Useful? But again filtering out the very small samples which look like they were added in error.

**Comment by johnvanbreda** [comment]
As a quick starting point for this, here's the results of a query for the first 4 bits of information:

```
"Count of samples with at least 5 occurrences"	"926"
"Combined count of samples/lists with at least 5 occurrences"	"2583"
"Count of lists with at least 5 taxa"	"1657"
"Count of users"	"612"
```

Looking at the People page on the website (logged in as admin) I can count the fact that there have been 44 different users logging in to the website over the last month. This data is in Drupal, not Indicia, so I can't integrate it in the above report. I'm not sure if it is worth a dedicated view to make it easier to extract this information?

And, for my own reference, here's the SQL for the first query:
```sql
select 'Count of users' as statistic, count(distinct user_id)
from users_websites
where website_id=93
union
select 'Count of samples with at least 5 occurrences', count(*) from (
  select sample_id
  from cache_occurrences_functional
  where website_id=93
  group by sample_id
  having count(*) >= 5
) as subquery
union
select 'Count of lists with at least 5 taxa', count(*) from (
  select l.id
  from scratchpad_lists l
  join scratchpad_list_entries e on e.scratchpad_list_id=l.id
  where l.website_id=93
  and l.deleted=false
  group by l.id
  having count(*) >= 5
) as subquery
union
select 'Combined count of samples/lists with at least 5 occurrences', (select count(*) from (
  select sample_id
  from cache_occurrences_functional
  where website_id=93
  group by sample_id
  having count(*) >= 5
) as subquery) + (select count(*) from (
  select l.id
  from scratchpad_lists l
  join scratchpad_list_entries e on e.scratchpad_list_id=l.id
  where l.website_id=93
  and l.deleted=false
  group by l.id
  having count(*) >= 5
) as subquery2)
```

**Comment by johnvanbreda** [comment]
Since @HDean has asked for the registered user count since the start of the FY and @Davydaveth has asked for a different filtered count based on last log in, I've created a simple view which counts all properly registered users with the ability to filter by registration date or last login date. See https://www.brc.ac.uk/pantheon/user-stats

**Comment by HDean** [comment]
This is great, thanks John.

**Comment by johnvanbreda** [comment]
Here's a data table showing the accumulation of samples and lists over time (@Davydaveth's last request): https://www.brc.ac.uk/pantheon/content/data-accumulation-table

**Comment by Davydaveth** [comment]
That accumulation table is great John, and I have graphed it and might do a short write up for our Chief Scientist. It really shows the growth in use, and is an avenue for continued support. I'm not sure we need a dedicated page on this stuff as such, but having the ability for someone to run that SQL and yield the current results would, sporadically, be useful. Perhaps sharing admin rights (if not already done) in CEH might be a path to easily be able to call on those stats when the infrequent need arises?

**Comment by johnvanbreda** [comment]
I've added a menu item "Admin pages" for anyone with admin rights. This gives a page where you can access links to the species editor and data accumulation reports (plus any other tools we add in future).
