### ISSUE TITLE
ISIS reporting to follow the ISIS spreadsheet reporting layout

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#24]
Tabular version, that follows the original ISIS output, is required as well as current nested version.

**Comment by johnvanbreda** [comment]
Example can be obtained from the original ISIS spreadsheet (Jon). Score is the total ISIS score for each included species, divided by number of species, \* 100.

**Comment by johnvanbreda** [comment]
I think this is now replaced by the SATs table available within the tabular ISIS output.

I’ve added reported condition to the SATs table within ISIS but would appreciate confirmation I’ve got the right idea. 
1. Firstly, am I right in saying the condition can only be applied to the SATs table? 
2. Secondly, can you confirm what the threshold numbers are related to. Currently I’ve compared these to the number of species for that SAT in the sample, so a condition is favourable if there are at least <threshold> species in the sample for that SAT.

**Comment by HDean** [comment]
Hi John,
1. yes, condition is only applied to SATs
2. the favourable/unfavourable condition is based on a straightforward count of the number of species with that SAT within the sample. Attached is the list of thresholds for each SAT - ignore the ones for F004-F010 (the ones that are not integers). The minimum sample size is 15 species (although this will need to be double checked with David H as the min sample size used to be used for a calculation using the now redundant BATs).
   [ISIS thrsholds.xlsx](https://github.com/BiologicalRecordsCentre/Pantheon/files/519803/ISIS.thrsholds.xlsx)

**Comment by johnvanbreda** [comment]
Thanks Hannah. We'd already imported the threshold data from the previous import - the import includes the BAT thresholds which are now defunct but I don't think that matters. From a quick scan it looks like all the SAT values are the same (see https://github.com/Indicia-Team/support_files/blob/master/Pantheon/Pantheon%20Data%20Importer%20for%20v3.7.2/isis_thresholds.sql to see the version we imported) so I don't need to change anything.

One question though - if the comparisons are done on a simple threshold against the number of matching species in the sample, then why are several of the threshold values fractions, e.g. the ones for F... codes (Open Habitats)?

**Comment by HDean** [comment]
Hi @johnvanbreda,

I asked the same question! They can be ignored. They were used for some other calculation to do with the BATs. So there are no thresholds for these SATs.

**Comment by HDean** [comment]
Getting confused - the fractions are nothing to do with BATs! But Jon W did say to ignore them. His exact words "Do not include these as they are not used for CSM"

**Comment by johnvanbreda** [comment]
Ah, OK, so the F0... codes are not actually BAT codes but something else. In which case I think this issue is done and can be closed?

**Comment by HDean** [comment]
I agree - this can now be closed.
