### ISSUE TITLE
Reporting on the "distance" found in a sample from the Favourable status default threshold

### ISSUE THREAD

**Issue by Davydaveth** [BiologicalRecordsCentre/Pantheon#242]
A few users have commented that in site surveys they would like to know how far from a Favourable status position their samples actually are. At the moment, ISIS-compliant surveys just flag up either Unfavourable or Favourable. There is reported value in being able to say, for example, that Sample A is only 2 species below Favourable for Assemblage Y; at the moment all they can say is that it is not Favourable.

Action:
Add the default Assemblage species threshold value to the report: this is currently fixed for each assemblage so a non-varying figure. It would sensibly appear next to the Reported Condition field.
Add the default scores table to the Reported Condition page and, ideally, to each Assemblage.

**Comment by Davydaveth** [comment]
I note that i added the default score for each assemblage that was written up in The Glossary, though this is buried and still does not present the full assemblage list to the user, so the issue still stands

**Comment by johnvanbreda** [comment]
I suggest that we display the species count/threshold ratio next to the condition, e.g. Unfavourable (7/9). The threshold is currently in the report query but the column is hidden.
