### ISSUE TITLE
An assemblage tab as part of the main analysis tab toolkit

### ISSUE THREAD

**Issue by Davydaveth** [BiologicalRecordsCentre/Pantheon#244]
Given the importance of the ISIS assemblages in analysis (both I and a number of consultancies regularly mine them), having the assemblages accessed in the way it is remains cumbersome. I suggest having an "Assemblages" tab as one of the principal analysis routes open to a sample. This would then sit next to “Habitat scores” etc.
The tab would display the standard Assemblage page as it relates to the sample being analysed.

**Comment by johnvanbreda** [comment]
Done. @Davydaveth can the SATS tab be removed from the habitats and resources tabular page since it is a duplicate?

**Comment by Davydaveth** [comment]
yes, that seems sensible John, as it gives exactly the same information from the sample. 

I guess, if there are resources left at the "end" of contract, it might be useful to have a field selection option as part of that assemblage output, if that is easy to do. The focus there would be the association of the SAT with the habit-resource hierarchy, so you might want to drop "broad habitat" from the output, or add in the Resources which together are utilised by the Assemblage in that sample. It also addresses the one-off issue of being able to establish the "resource-composition" of a SAT by feeding Pantheon a SAT species list and assessing its resource needs. Would be a nice textual addition to the SAT description.

**Comment by johnvanbreda** [comment]
I've added the columns picker button. However I'm not sure how to calculate the resources for an assemblage. An assemblage is a child of a biotope or habitat and a habitat then contains child resources. E.g this could be depicted as the following (data from my test sample https://www.brc.ac.uk/pantheon/habitats-resources/isis-assemblages?dynamic-sample_id=853&dynamic-sample_type=scratchpad#):

* biotope: open habitats
  * habitat: short sward and bare ground
    * SAT: open short sward

* biotope: open habitats
  * habitat: short sward and bare ground
    * resource: habitats >> sward/field layer
    * resource: habitats >> exposed sand
    * resource: soil type >> sand
    * resource: habitats >> litter & ground layer

So, given the above, can we assume that all 4 resources are used by the open short sward assemblage? If not, how else can I make this link?

**Comment by Davydaveth** [comment]
It gives as much indication of resource use as does the Associated species listings do for the associated species use. Given that the assemblage species pool is fixed, and each species will match a number of resources,  then one does get an indicative resource picture for that assemblage. We just have to explain to the user, as with Associated species, that the results are generically true but may not be site-specific. It would seem to yield the totality of resource-dependency for any particular SAT.

**Comment by johnvanbreda** [comment]
@Davydaveth Ok, so is everything done that you need for this change now?

**Comment by Davydaveth** [comment]
Hi John.
Yes, we can close this issue down now. Makes a huge difference being able to access the assemblages so quickly.
