### ISSUE TITLE
Record page number required also at the page head- minor workflow tweak

### ISSUE THREAD

**Issue by Davydaveth** [BiologicalRecordsCentre/Pantheon#249]
With long sample lists, workflow is interrupted by having to scroll down to the page bottom to move to the next sample page. Replicating the record page list at the top of Add Data/My species lists/ My lists, but under the "Paste new Species list option, would ease this. Perhaps making the "Paste new species list" entry more distinct might be required so as to avoid clutter there after implementation.

**Comment by johnvanbreda** [comment]
Added to the My Species Lists page (and button restyled) as well as to a couple of other pages (the species list for an analysis for example).
