### ISSUE TITLE
Add minimum sample size requirements

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#25]

**Comment by johnvanbreda** [comment]
@e.g. if species sample is less than x recognised species (40?) there would be a warning on ISIS to say your sample is too small so output may not be reliable.

**Comment by johnvanbreda** [comment]
@hdean Given the changes in terminology, can you confirm exactly where this warning should appear and what the threshold should be please.

**Comment by HDean** [comment]
@johnvanbreda 
The threshold is 15.
The threshold relates to the SQI so should appear where ever there is a SQI calculated in the Habitats & resources reports.

**Comment by johnvanbreda** [comment]
Done. Note the warning is generated on a per-row basis, not per sample. For example if you have 100 species in a sample but only 10 are coastal, then the warning only appears on the coastal row of the broad biotope table.
