### ISSUE TITLE
More efficient space use within the "My lists" pages

### ISSUE THREAD

**Issue by Davydaveth** [BiologicalRecordsCentre/Pantheon#251]
The size and placement of the options to work on lists in "My lists" (e.g. edit, delete etc) now wastes much screen space and reduces the number of lists on a page. With a large number of lists this dramatically increases the number of pages over which they are now spread. Placing the option set underneath each of the lists would seem to allow more efficient packing. This needs to be set against easy reading and design, but seems worth pursuing.

**Comment by johnvanbreda** [comment]
I've converted 2 buttons to icons (where an obvious icon was available) and changed the layout a bit so it takes much less space.
