### ISSUE TITLE
Statuses are missing for some species groups

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#252]
Andy Jukes reported that Andrena niveata was not showing its Red Data status, but as far as I can see all Andrena species have lost any conservation status information, and all the Lasioglossum as well. Bombus seems to have the various priority lists but not any rare/scarce info.

At least one ground beetle genus has also lost its status info.

Could there be a problem with taxa that are no longer displaying a subgenus? UKSI took the decision to remove subgenera from some species groups, but the subgenera are still used in the JNCC status spreadsheet, is that causing problems or is something else going on?

**Comment by johnvanbreda** [comment]
This was a bit of a mess as designations are linked to specific name versions and the UKSI now has new names for bees as well as some other stuff. I've re-imported and massaged the data to link to the correct versions of names.
