### ISSUE TITLE
Pantheon still cannot count!!

### ISSUE THREAD

**Issue by AdrianPKnowles** [BiologicalRecordsCentre/Pantheon#254]
The summary table of species by taxonomic order is still miscounting.  The attached list has 394 species.  The summary tab suggests that 382 have been analysed whilst 12 have not.  The correct values are 380 and 14.

90 beetles are included within the list.  The taxonomic table says there are 88 analysed but when you click on the hyperlink to list them, there are 87 in the list, which is correct because three are not analysed. So, something has been counted in the "analysed" list twice.  I have checked and it is NOT because one of the "not analysed" species has sneaked in there.

similarly, the "analysed" table value for Diptera is 60 but there's only 59 in the list.

Adrian
[Abberton species list for testing.xlsx](https://github.com/BiologicalRecordsCentre/Pantheon/files/3835483/Abberton.species.list.for.testing.xlsx)

**Comment by johnvanbreda** [comment]
Fixed. The data on the summary page included species that had a keyword tagged against them as being analysed when they shouldn't really be.

**Comment by AdrianPKnowles** [comment]
Thanks John

**Comment by AdrianPKnowles** [comment]
John,

I’d assumed that your fix was universal, but I’m now working on a different dataset and the same thing is happening – mis-match between the summary overview numbers and the actual number of species involved.  Do you need my species list to sort it out?

 

Best wishes

Adrian
