### ISSUE TITLE
Login problems

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#256]
A Pantheon user has just reported that he can only log in by requesting a new password, which then has to be requested again for the next log in, etc.

I've just tried to log in using the username and password that I have always used and that is not being accepted (I haven't yet tried requesting a new password).

@johnvanbreda is there any underlying problem with logins at the moment?

**Comment by kitenetter** [comment]
I have now reset my own password, and in the process discovered that I may have been trying to use the wrong password the first time round, so this is perhaps a user-specific problem not a general one.

If it's easy to do can I set be given admin rights to Pantheon so that I can masquerade as another user?

**Comment by kitenetter** [comment]
@johnvanbreda this problem has been reported again (from the same user I think):

"Last year I emailed about the fact that every time I tried to log into Pantheon, the password (remembered on my computer or entered again from my password records) was not recognised, and the only way I could log -in was to go through the forgotten password procedure and reset it. This is still happening even when I let Pantheon set the password to its own auto-generated one, and it is getting quite annoying. Surely it can't just be me that this is happening to? If it is just me, any suggestions on how to resolve the issue?"

I haven't had reports from anyone else.

Is it possible to give me admin permissions for Pantheon so that I can try resetting the password from within the website People list?

**Comment by kitenetter** [comment]
I do now have admin rights (thanks @BirenRathod). 

It turns out that the user mentioned in the previous comment was struggling because he was trying to log in using his email address, rather than his username. Pantheon insists on having the username.

Two questions:
1. Is it possible to set the login page so that it allows users to log in with either an email address OR a username?
2. If that isn't possible, can we edit the login page so that it makes it clear that a username is required? (I can't find a way of editing that page.)

**Comment by BirenRathod** [comment]
@kitenetter 
I have implemented the log in procedure , so user can now login using either of it. If you still need to add any text let me know and I can help you in that direction.

**Comment by HDean** [comment]
Closing as this has now been resolved.
