### ISSUE TITLE
New traits table development

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/Pantheon#261]
1. Change the table of traits at https://www.brc.ac.uk/pantheon/explore/traits so that it is dynamically generated. The values in the number of species column are modified into hyperlinks, which link to a filtered view of the species index table for species linked to that trait. Yes
2. For each row in the table of traits described above, add an extra link “resource details”. This takes you to a hierarchical view of the resource hierarchy inside that trait, showing the code and species count for each (as per the example for peat shown above).
3. Optional – add a column for each row in the resource details breakdown which shows the output of some metric that indicates the conservation importance of the species associated with that resource. E.g. SQI rarity score, or perhaps, a count of the taxa with a valid conservation status. 
4. Add to the count and “importance” metric values, a bar chart style display of the value, so that the user can instantly visualise where the important stuff is.

**Comment by johnvanbreda** [comment]
Initial implementation at https://www.brc.ac.uk/pantheon/explore/traits-2.

**Comment by Davydaveth** [comment]
1st Observation comments.
The SQI sample size filter needs to operate here as it does with samples. Perhaps the  blue can turn red?
SATs are being pulled across in the wider habitat trawl, but that report nothing so are fairly useless. I would filter SATs out, as they are reported on in their own right further down the list.
It feels like a tabular as well as graphical representation is necessary, so as to align with the  Habitats & Resources module for lists & samples.
There are some strangely large (enormous!) SQI being reported with very low species numbers being in the underlying calculation. Open habitats/upland/habitats/nests/ant nests has 1 species with a SQI = 800!

There are a number of NIU in the graphic. Are they unpopulated database fields? They seem to have zero species.  We should filter them out I think. 
A wider consideration is whether we should tidy the data table at some time to purge redundancy, though it will make zero impact on efficiency i would imagine.

For the number of species report (following the hyperlinked value) it would be nice if the species table could filter by first entry resources. So for Saline lagoon, all the  aquatic sparsely vegetated would be in a block, then all the aquatic well vegetated. Admittedly, this might be easier to achieve in a sort of a downloaded spreadsheet of those data. depends how hard the ask is to execute.

**Comment by johnvanbreda** [comment]
* I've added a warning triangle and changed the colour of the SQI bars if the sample size is small.
* SATs removed.
* For a tabular output, is it just a single table, with biotope/habitat/resource in column 1, then code, then species count and SQI columns?
* The example you give has a single taxon _Microdon mutabilis_ sens.lat. with a rarity score of 8. Since the SQI is the average rarity score * 100, 800 is correct in this case?
* NIUs removed.
* I'm not sure the idea of sorting the species by resource into a block is possible, because species can have multiple resources?

**Comment by johnvanbreda** [comment]
Now complete, at https://pantheon.brc.ac.uk/explore/whole-db-traits.
