### ISSUE TITLE
Error in download of data - Habitat & Resources tabular list level 3

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#262]
This email came into the Pantheon inbox:

Hi,
Just wanted to flag that there are consistent issues with attempting to download the following output from Pantheon:

Habitats and Resources: Tabular: List
Resources and Other Level 3

Resources section will not download and the following error message is generated:

{"error":"There was an SQL error: ERROR:  syntax error at or near \"select\"\nLINE 37:       join join (select distinct cttl.preferred_taxa_taxon_l...\n                          ^ - \n    select id as \"id\",\n'5088' as \"sample_id\",\n'scratchpad' as \"sample_type\",\nterm_id as \"term_id\",\nparent_r_id as \"parent_r_id\",\nbb_term as \"bb_term\",\nsb_term as \"sb_term\",\nterm as \"term\",\nspeciescount as \"count\",\ncase when sub.rep<1 then '<1' else round(sub.rep)::varchar end as \"rep\",\nsqi as \"sqi\",\ncons_count as \"cons_count\",\ncons as \"cons\"\n    from (\n      select t_r.id as \"id\",\n        t_r.id as \"term_id\",\n        case when p.id=t_sb.id then 0 else t_r.parent_id end as \"parent_r_id\",\n        t_bb.term as \"bb_term\",\n        t_sb.term as \"sb_term\",\n        case when p.id=t_sb.id then '' else p.term || ' >> ' end || t_r.term as \"term\",\n        count(distinct cttl.preferred_taxa_taxon_list_id) as \"speciescount\",\n        count(distinct cttl.preferred_taxa_taxon_list_id)::float * 100 \/ (\n          select count(distinct ttlsub.preferred_taxa_taxon_list_id)\n          from cache_taxa_taxon_lists ttlsub\n          join taxa_taxon_list_attribute_values avsub\n            on avsub.taxa_taxon_list_id=ttlsub.id\n            and avsub.taxa_taxon_list_attribute_id=17\n            and avsub.int_value=t_r.id\n        ) as \"rep\",\n        sqi.sqi,\n        nullif(count(distinct case when ttd.taxon_id is null then null else ttl.taxon_meaning_id end), 0) as \"cons_count\",\n        string_agg(coalesce(td.code, td.abbreviation), '|' order by td.code) as \"cons\"\n      from cache_termlists_terms t_bb\n      join taxa_taxon_list_attribute_values av_bb on av_bb.int_value=t_bb.id\n        and av_bb.taxa_taxon_list_attribute_id=15 and av_bb.deleted=false\n      join join (select distinct cttl.preferred_taxa_taxon_list_id\n        from cache_taxa_taxon_lists cttl\n        \n\n\n          join scratchpad_list_entries sle on sle.entry_id=cttl.id\n              and sle.scratchpad_list_id in (5088)\n        \n      ) cttl on cttl.preferred_taxa_taxon_list_id=av_bb.taxa_taxon_list_id\n      join taxa_taxon_lists ttl on ttl.id=cttl.preferred_taxa_taxon_list_id\n      join taxa_taxon_list_attribute_values av_sb on av_sb.taxa_taxon_list_id=cttl.preferred_taxa_taxon_list_id and av_sb.deleted=false\n        and av_sb.taxa_taxon_list_attribute_id=16\n      join cache_termlists_terms t_sb on t_sb.id=av_sb.int_value and t_sb.parent_id=t_bb.id\n      join taxa_taxon_list_attribute_values av_r on av_r.taxa_taxon_list_id=cttl.preferred_taxa_taxon_list_id and av_r.deleted=false\n        and av_r.taxa_taxon_list_attribute_id=17\n      join cache_termlists_terms t_r on t_r.id=av_r.int_value\n          -- exclude subheadings - GitHub #53\n          and t_r.term not in (\n          'base status','humidity','terrestrial aspect','habitats','soil type','flow',\n          'woodland habitat','soil humidity','tree species','conifer or broadleaved'\n          )\n      join cache_termlists_terms p on p.id=t_r.parent_id and (p.parent_id=t_sb.id or t_r.parent_id=t_sb.id)\n      left join (\n        select av_r1.int_value as r_id, round(avg(rscv.int_value)*100) as sqi\n        from (select distinct cttl.preferred_taxa_taxon_list_id\n          from cache_taxa_taxon_lists cttl\n          \n\n\n          join scratchpad_list_entries sle on sle.entry_id=cttl.id\n              and sle.scratchpad_list_id in (5088)\n        \n        ) as sub\n        join taxa_taxon_list_attribute_values av_r1 on av_r1.taxa_taxon_list_id=sub.preferred_taxa_taxon_list_id and av_r1.deleted=false\n          and av_r1.taxa_taxon_list_attribute_id=17\n        join taxa_taxon_list_attribute_values rscv on rscv.taxa_taxon_list_id=sub.preferred_taxa_taxon_list_id and rscv.deleted=false\n          and rscv.taxa_taxon_list_attribute_id=24\n        group by av_r1.int_value\n      ) as sqi on sqi.r_id=av_r.int_value\n      left join (taxa_taxon_designations ttd\n        join taxon_designations td on td.id=ttd.taxon_designation_id and td.deleted=false\n        join cache_termlists_terms cat on cat.id=td.category_id and (\n             (cat.term='GB Red List' and coalesce(td.code, td.abbreviation) not in ('LC', 'NA', 'pLC', 'pNA', 'NE'))\n          or (cat.term='GB Status' and coalesce(td.code, td.abbreviation) not in ('None', 'Not reviewed', 'Not native', 'NA'))\n          or (cat.term not in ('GB Red List', 'GB Status'))\n        )\n      ) on ttd.taxon_id=ttl.taxon_id and ttd.deleted=false\n      group by t_r.id, t_r.id, case when p.id=t_sb.id then 0 else t_r.parent_id end, t_bb.term, t_sb.term, sqi.sqi,\n        case when p.id=t_sb.id then '' else p.term || ' >> ' end || t_r.term\n    ) as sub\n    where 1=1\n   ORDER BY count desc LIMIT 20001","code":44,"file":"D:\\websites\\warehouse\\system\\libraries\\drivers\\Database\\Pgsql.php","line":352,"trace":[]}

**Comment by johnvanbreda** [comment]
Fixed by https://github.com/BiologicalRecordsCentre/indicia-reports/commit/2f0daa7513dcfc7ed6f8ec1988207a3e5a59b642
