### ISSUE TITLE
Editing traits on Admin pages

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/Pantheon#264]
The species editing tool on the Pantheon admin pages currently shows an incorrect list of available terms if you add additional rows to the broad biotopes, habitats or resources data for a taxon.

**Comment by johnvanbreda** [comment]
The reason is the complex attribute grids on this page store the list of terms in JavaScript, so they are available when adding new rows. The key name given to each list of terms is only unique within the control, but there are multiple controls on the page so the last one (plant associated) overwrites the other lists of terms.

**Comment by johnvanbreda** [comment]
Now fixed. Note that one of the suggestions was that the biotope, habitat and resource attribute drop-downs should only be populated with the relevant terms. Is it safe to assume that the top level  in the hierarchy is always broad biotopes, their direct children are habitats, and any descendants of the habitats are resources?

**Comment by HDean** [comment]
Yes, it is a safe assumption that the top level in the hierarchy is always broad biotopes, their direct children are habitats, and any descendants of the habitats are resources. The diagrams can be seen here: https://www.brc.ac.uk/pantheon/content/habitats-and-resources and click on the broad biotope name. I did have a nagging feeling that it wasn't quite so straightforward but I can't see anything that doesn't fit with the hierarchy.

**Comment by johnvanbreda** [comment]
Ok, the hierarchies are now limited to the correct levels.
