### ISSUE TITLE
Question: what does "Reset report" do?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#278]
On this page:
https://pantheon.brc.ac.uk/species-lists/my-list

there is a button "Reset report" that I don't recall seeing before. What does it do?

**Comment by johnvanbreda** [comment]
It was added during a recent round of updates. The page now remembers pagination and sort information when reloaded, so this button will appear in that instance, allowing you to reset it to the default view.

**Comment by kitenetter** [comment]
I can no longer see a "Reset report" button, and in any case this does not seem to be causing problems - closing.
