### ISSUE TITLE
Unable to delete temporary list

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#279]
On this page:
https://pantheon.brc.ac.uk/species-lists/my-list

it should be possible to delete lists by using the red minus button, This is not working.

**Comment by johnvanbreda** [comment]
This is another consequence of the site URL changing, as the path is embedded in some JavaScript on the page.

@BirenRathod has the Pantheon site been moved to Pantheon? If so can I have access please?

**Comment by BirenRathod** [comment]
@kitenetter I implemented urls in several places. could you check if you can delete records?

**Comment by BirenRathod** [comment]
@johnvanbreda & @DavidRoy Info: This is not yet on Pantheon but it is in the list.

**Comment by johnvanbreda** [comment]
@BirenRathod I found the delete still didn't work, but I changed the URL to the website in the node.420.js file and that has now fixed it.

**Comment by BirenRathod** [comment]
Thanks @johnvanbreda. That is the one.

**Comment by kitenetter** [comment]
I think we can close this.
