### ISSUE TITLE
Contact page not available

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#280]
This page:
https://pantheon.brc.ac.uk/content/contact

produces "Page not found".

**Comment by DavidRoy** [comment]
@BirenRathod can you look into this please

**Comment by kitenetter** [comment]
I think I've fixed it - seems to have just been an incorrect link from this page:
https://pantheon.brc.ac.uk/content/contact-us

Having edited that link, the contact form is now visible again. Closing.
