### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#287]
A user reports that they cannot log in to Pantheon:
"it’s been saying 'Unrecognized username or password' with the right ones for a bit. tried to reset and nothing"

I've just tried to log in and am also unable to do so.

@johnvanbreda please can you investigate.

**Comment by kitenetter** [comment]
I can log in again now. @HDean do you know if anyone is still reporting this problem?

**Comment by HDean** [comment]
No, not heard from anyone. People have been using it too as two different people have reported to me that the combined summary reports are not working #288.

**Comment by kitenetter** [comment]
Closing this one.

**Comment by kitenetter** [comment]
Have had reports from two people at Buglife that they are still unable to log in. Am awaiting feedback as to whether clearing cache/cookies will make any difference.

**Comment by HDean** [comment]
Hi @kitenetter and @johnvanbreda,
I am now having this problem. When I try to log in, I get an error. When I reset my password I can then get access but once I log out and try to log back in again, then I get an error again and have to reset my password!

**Comment by HDean** [comment]
Having looked at a previous issue, it turns out that logging in using my email address is the problem and that I should be using username (will just need to try and remember what it is!)

**Comment by johnvanbreda** [comment]
I've enabled the module that allows logging in via email or password - does that help?

**Comment by HDean** [comment]
That worked for me :-)

I had also found out what my username is and was able to log in with that! So it looks like both work now.

**Comment by HDean** [comment]
Closing issue as we have not heard any more about people not being able to log in. I can log in with either username or email.
