### ISSUE TITLE
Combined summary not working

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#288]
A user reported and I have confirmed that when you try to create a combined summary report you get the following error message:

'The website encountered an unexpected error. Please try again later'

Error first report 28th June, still happening today (3rd July)

**Comment by kitenetter** [comment]
Still happening at 18 July (was trying to do a Pantheon demo over the weekend).

@johnvanbreda is this an easy fix?

**Comment by johnvanbreda** [comment]
@BirenRathod I have pushed a fix to this into the dev site but I don't have permission to push it to test and live. Please can you do that for me (or give me permissions)?

**Comment by BirenRathod** [comment]
@johnvanbreda Try again to see if that works. If not I will do it for you.

**Comment by johnvanbreda** [comment]
Thanks @BirenRathod, that worked.

**Comment by johnvanbreda** [comment]
Now fixed.
