### ISSUE TITLE
Incorrect conservation status information being displayed

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#290]
Recently (in the last few weeks I think) there has been a change to the conservation status data that Pantheon displays, whereby a lot of outdated statuses are now being shown. This has caused concern among users.

Example: beefly Villa cingulata was showing as status "LC;NR", but is now "NR;NR-includes;RDBGB.EN;RDBGB.VU".

Has something changed in UKSI to cause this, or is there another explanation?

**Comment by HDean** [comment]
Some further examples:
Agrilus sinuatus was demoted years ago as was Long-winged conehead and these had been cleared until last month ...now the old statuses have been reapplied (showing as Na;RDBGB.VU;WO9ii)


helochares lividus was also demoted years ago and not given as NB for years until last  month ditto Phiolodromus albidus whcih is now ubiquitous in Lowland England!

**Comment by johnvanbreda** [comment]
I think I know what has happened. After the incremental UKSI updates, we run a script which corrects designations that point to an old, redundant synonym to point to the current accepted name, in order to keep things clean. I suspect that many old designations were in this state and were thus hidden, therefore by "fixing" the data we have unhidden them.

I'm in the midst of a warehouse release so will look at this once I've completed the work on the release.

**Comment by johnvanbreda** [comment]
The issue wasn't actually the incremental updates, but after the last full UKSI update in April I don't think things were cleaned up properly and a lot of the designations that are still in UKSI made their way back into the system.

I've done a full rebuild of the designations information so it should be OK now.

**Comment by kitenetter** [comment]
@johnvanbreda we discovered this morning that the species download page is not accessible to standard logged in users. I assume there must be a permissions setting somewhere, but I can't find it.

Options:
1. Can we make that page available to standard logged in users?; or,
2. I can remove the link to the download page and just point out to people that a download option is available at the top and bottom of the main species index page.

**Comment by kitenetter** [comment]
However, there is a further issue in that the download links that appear at the top and bottom of the table on the "Species index" page output a csv that displays the unhelpful 'span' formatting:
`<span class="designation-class-legallisting">Legal listing (1)</span>`

whereas the download from the "species index download" page outputs a csv without the 'span' formatting. So we need to enable option 1.
