### ISSUE TITLE
Revision to Sample summary & new Guilds page

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/Pantheon#3]
E.g. http://www.brc.ac.uk/pantheon/pantheon/summary?dynamic-sample_id=312083
1. Remove Guild output section
2. Add additional report button: 'Ecological Guilds'
3. Change report element (currently % of sample analysed) to % of sample not-analysed.  Make a hyperlink to the list of species

**Comment by johnvanbreda** [comment]
Ecological Guilds page will have 2 tabs. First tab is a grid similar to the current guilds grid on the summary, but with the first column split into 2 (adult/larva, resource). Filter drop down at the top of each of these columns so you could, for example examine all data for a specific resource or for larva only.
2nd tab shows a pie chart of adult resources plus a 2nd chart for larva resources. Pie slice size is the number of species.

**Comment by HDean** [comment]
HI @johnvanbreda 

There are a couple of things that need updating on the Ecological Guilds summary:
1. there needs to be a back to summary button.
2. Can there be a link from the count of species to the species list.

**Comment by johnvanbreda** [comment]
Done

**Comment by HDean** [comment]
Great. All done. Closing issue.
