### ISSUE TITLE
Allow users to flag up errors in the data

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#31]

**Comment by johnvanbreda** [comment]
Could use a simple Drupal feedback form? Simply an ability to log a text comment for Hannah to review.

**Comment by johnvanbreda** [comment]
@hdean Is a simple form with title and description of problem all that is needed? If so where/how should it be accessed?

**Comment by HDean** [comment]
@johnvanbreda - yes I think that would seem sensible. I was thinking that we could a link to it from the "Contact Us" page? What would happen to the feedback? Where does it get stored, who has access to it?

I'll check with Jon W what his thoughts on this are, i.e. is it needed at this point?

**Comment by johnvanbreda** [comment]
Yes, the Contact Us page would be a good place. The posted comments would be stored as Drupal content. I'd set up a view page which lists all the comments so you can browse them. Potentially we could also add a notification so you know when one is added.

**Comment by HDean** [comment]
Hi @johnvanbreda ,
Would it be possibly to add a simple form for collecting feedback to the "Contact" page? I think this is the best option for now.

**Comment by johnvanbreda** [comment]
I've added a link to the contact form (this was slightly easier than embedding the form).

**Comment by HDean** [comment]
Hi @johnvanbreda 
I've just tried the link and when I click on it, I get the following message: "Access denied
You are not authorized to access this page."

**Comment by johnvanbreda** [comment]
Permissions fixed.
