### ISSUE TITLE
Create new Species List output

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#32]

**Comment by johnvanbreda** [comment]
Revisions to the species list output tables:
- Need ability to hide/show columns (could this be based on our responsive table code?). Or, maybe several different optional species list report outputs.
- Traits output in species list, break down into habitat, resource and trait columns. Trait column should show hierarchy, e.g. branches >> aerial branches.
- Add ISIS score (in addition to code column). Attribute should be available in DB
- ISIS code column needs to include specific assemblage types (F111 rather than F1 etc)

**Comment by HDean** [comment]
Requirements for output in attached file.
[Species Index Mockup 2016.docx](https://github.com/BiologicalRecordsCentre/Pantheon/files/270775/Species.Index.Mockup.2016.docx)

**Comment by johnvanbreda** [comment]
Please confirm:
1) What are SAT and BAT codes for ISIS? I presume they replace the current ISIS code column which was the code attached to the ecological division (now called broad biotope). Therefore I am guessing that the SAT code might be the code attached to the habitat (now called specific habitat)?
2) Is the ISIS score what we've labelled the rarity score?

**Comment by HDean** [comment]
BAT (broad assemblage type) code is the value that is currently in the ISIS code column and is single letter followed by a single number, e.g. F1.
SAT (specific assemblage type) code is a single letter followed by 3 numbers, e.g. F112.

The BAT and SAT codes can be broadly equated to the broad biotope and specific habitats respectively although they are separate from the Osiris traits.
(However, Jon W did mention on Friday (12/08) the possibility of amalgamating ISIS with Osiris but this  is not definite.)

The ISIS score (which in the mock-up document is referred to as the conservation score) must be the rarity score as these are the only scores that are currently available in the database. I will double check this with Jon W.

**Comment by HDean** [comment]
I've confirmed with Jon that the ISIS score is the rarity score. At present the rarity score will only be used in Species Index as just a value, i.e. the species has a rarity score of 4.

These scores were used to calculate a conservation score within Horus but this is being scrapped for now.

**Comment by johnvanbreda** [comment]
Here's a link to the new Species Index page.: http://www.brc.ac.uk/pantheon/species-index. I'll add it to the menu when you are happy with it.

**Comment by johnvanbreda** [comment]
Given comments elsewhere, should I now remove the ISIS score (rarity score) column?

**Comment by HDean** [comment]
Yes, the rarity score can be removed. The data should remain in the database as it may be that they are revised and used in the future.

**Comment by johnvanbreda** [comment]
Done

**Comment by johnvanbreda** [comment]
After review from Jon, proposed columns:
Species
Family
Order
Conservation Status
Horus Status
Larval Guild
Adult Guild
Broad biotope (Osiris)
Habitat (Osiris)
Resources and traits (Osiris)
SAT (Isis)

**Comment by johnvanbreda** [comment]
Hi @HDean, a few questions:
How is the Horus status derived? Is it the same as the Horus indicator we currently have? If not can I have an example of what it should show please.
Given #38, I think the "Habitat (Osiris)" column should really be "Specific biotope (Osiris)"
Are we dropping the ISIS BAT code?
Is the SAT column output the same as the previous ISIS SAT Code column?

**Comment by HDean** [comment]
Hi @johnvanbreda, 
1. Not sure about Horus status. I have it on my list to discuss at tomorrow's meeting.
2. I agree, Habitat (Osiris) column should really be Specific biotope (Osiris)
3. Yes, we are dropping the BAT code (in everything, it will no longer be in the database)
4. Yes, the SAT column is the same as the previous ISIS SAT code. However, I think the wrong code is being used for the SAT code - what is currently showing is the specific biotope code. For example, Abdera biflexuosa is showing a SAT code of DW28 (sapwood & bark decay) when it should show A212 (which is also called sapwood & bark decay).

**Comment by johnvanbreda** [comment]
Additional points after teleconference:
- Add a traits search box to the top to make searches easier
- There is a problem with some duplication of species in the list
- Remove HORUS status.

**Comment by HDean** [comment]
Hi @johnvanbreda,

After our meeting yesterday, Jon realised that he was thinking about the Horus status incorrectly. It does need to stay in but it should list the indices and the score that is has.

The column title should be called something like Horus Indicator and Jon is envisaging it showing something like IEC2 if the species had a grade 2 within the Index of Ecological Community. Not sure how we show codes as currently it is the name of the trait that gives the indices title and the trait value that gives the grade.

**Comment by HDean** [comment]
Hi @johnvanbreda 
It appears that there is some information missing from the species index. The columns are there for:
- larval guilds
- adults guilds
- family
- order

but they do not contain any data.

**Comment by johnvanbreda** [comment]
Hi @HDean 
All fixed now. 
Cheers
John

**Comment by HDean** [comment]
Great! I think we can close this now as I can't see that there is anything more to do with the species list. The Horus changes are covered by a different issue.
