### ISSUE TITLE
Updating the Pantheon database with Species Designation data

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#36]

**Comment by andrewvanbreda** [comment]
John might have a differing opinion, but can't we just use the existing taxon_designation module to do this? The species are just held in the Indicia database in the usual way, so it seems to me that we should be able to use the taxon_designation module in the usual way. There is already a built-in Indicia importer for dealing with importing species designations.
The existing built-in Indicia taxon designation importer has the following instructions, providing you are able to provide data in this format, then the process should be very quick (I haven't used the importer personally, although there are other similar ones in the Indicia warehouse I have used, and the process is straightforward).
If we need to alter the format of any data you provide then this will take longer.

The instructions on the importer are as follows:

"This lets you import designations including links for any existing taxon, identified by the external key. To use this facility, create a spreadsheet with the following columns, or columns matching the JNCC Conservation Designations spreadsheet:

```
designation title
designation code
designation abbr
designation description
designation category
taxon
taxon external key
start date
source
geographic constraint
```

"

**Comment by DavidRoy** [comment]
Agreed. Hannah to take on the loading. There might then be a task to refine the UI to report the right designations

**Comment by johnvanbreda** [comment]
Is there an element to this of review of the designations in comparison with the JNCC spreadsheet to feed the changes back? Or will we end up with a partially duplicated overlapping set? Note that he JNCC designations are in the database as they are part of the UKSI upload, though we make little or no use of them yet.

**Comment by HDean** [comment]
I've created a spreadsheet using the JNCC one as a template. Let me know if I need to make any changes to it.
[20161010_DesignationDataForPantheon.xlsx](https://github.com/BiologicalRecordsCentre/Pantheon/files/519339/20161010_DesignationDataForPantheon.xlsx)

**Comment by johnvanbreda** [comment]
Hi Hannah
I've updated the designations list now using the new data on the test warehouse. The only comment from your perspective is I had to remove the rows with no TVK otherwise I can't link them to anything.

Some technical notes for my reference:
1) I needed to change a few column titles (see https://github.com/Indicia-Team/warehouse/issues/224)
2) Also remove the rows with a missing TVK then save as CSV.
3) After import, I ran the following query to remove any prior designations for groups that have had their designations updated by the import:

```
update taxa_taxon_designations ttd
set deleted=true
from taxa tall 
join taxa t on t.taxon_group_id=tall.taxon_group_id
join taxa_taxon_designations ttdimported on ttdimported.taxon_id=t.id
where ttd.created_on<'2016-10-25'
and ttdimported.created_on>'2016-10-25'
and tall.id=ttd.taxon_id
```

This solution needs care as any further updates to the UKSI dataset might undo the designations import, so they will need re-importing.

**Comment by HDean** [comment]
Hi @johnvanbreda ,
Many thanks for getting this done - I've let Jon know and he will get back to me if there are any concerns.

Most of the abbreviations used in the conservation status are included in the lexicon – is it possible to have the same link and hover-over that is included with the Osiris traits?

**Comment by HDean** [comment]
Apologies @johnvanbreda 
Something else I should have passed on to you. For the two designations, "Official_scarce_or_rare" and "Former_scarce_or_rare", if a species has a value in both, then only the official one should show. If a species only has a value for Former then this should still be shown. Is it possible to code this? If not, let me know and I will remove the data so there is only one value for official or former.

**Comment by johnvanbreda** [comment]
@hdean is this last question the same as #61?

**Comment by johnvanbreda** [comment]
Still to do : Most of the abbreviations used in the conservation status are included in the lexicon – is it possible to have the same link and hover-over that is included with the Osiris traits?

**Comment by johnvanbreda** [comment]
Conservation output now linked to Lexicon

**Comment by johnvanbreda** [comment]
Note for future updates - rather than apply the above cleanup script after the import, the following needs to be applied before:
```

select distinct tg.id as taxon_group_id
into temporary groups_to_remove
from taxon_groups tg
where title in ('centipede',
'insect - true fly (Diptera)',
'spoon worm (Echiura)',
'insect - true bug (Hemiptera)',
'insect - caddis fly (Trichoptera)',
'insect - stonefly (Plecoptera)',
'insect - butterfly',
'insect - hymenopteran',
'tunicate (Urochordata)',
'insect - cockroach (Dictyoptera)',
'coelenterate (=cnidarian)',
'insect - orthopteran',
'annelid',
'insect - earwig (Dermaptera)',
'bryozoan',
'mollusc',
'insect - beetle (Coleoptera)',
'crustacean',
'false scorpion (Pseudoscorpiones)',
'insect - mayfly (Ephemeroptera)',
'spider (Araneae)',
'millipede',
'sponge (Porifera)',
'insect - lacewing (Neuroptera)',
'insect - dragonfly (Odonata)',
'echinoderm',
'ribbon worm (Nemertinea)',
'insect - alderfly (Megaloptera)',
'insect - moth')

update taxa_taxon_designations ttd 
set deleted=true, updated_on=now() 
from taxa t
where t.id=ttd.taxon_id and t.taxon_group_id in (select taxon_group_id from groups_to_remove)

```

**Comment by johnvanbreda** [comment]
Additional note. Also run the following script after import to ensure designations are attached to the  preferred versions of names then rebuild the Pantheon species index.
```sql
select ttd.id, ttd.taxon_id, ttl2.taxon_id as new_taxon_id
into temporary to_fix
from taxa_taxon_designations ttd
join taxa t on t.id=ttd.taxon_id
join taxa_taxon_lists ttl on ttl.taxon_id=t.id 
join taxon_designations td on td.id=ttd.taxon_designation_id
join taxa_taxon_lists ttl2 on ttl2.taxon_meaning_id=ttl.taxon_meaning_id and ttl2.preferred=true and ttl2.taxon_list_id=15
where ttd.created_on>'2019-09-25'
and ttl2.taxon_id<>ttl.taxon_id;

update taxa_taxon_designations ttd
set taxon_id=new_taxon_id, updated_on=now()
from to_fix tf
where tf.id=ttd.id;
```
