### ISSUE TITLE
Error with entering date of birth when setting up user account

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#37]
Feedback from a user:

11 Apr 2016 – When setting up a new user account, it requests date of birth and provides a calendar pop-up, which has a year range only going back to 1999 – but you can enter the correct year manually. You are instructed to enter the date as the format dd/mm/yyyy, but it only accepts mm/dd/yyyy. Only niggles, I was able to create a new account.

**Comment by johnvanbreda** [comment]
This will be fixed when we do an update to the latest code - it's a bug that existed from a while back. 

The purpose of capturing the date of birth related to juniors signing up to iRecord - does Pantheon need to support people < 16 years old? If not we can just hide these fields.

**Comment by johnvanbreda** [comment]
Keep the same tick box as iRecord.

**Comment by HDean** [comment]
John, can you please update this when the code is updated? Thanks, Hannah

**Comment by johnvanbreda** [comment]
Fixed.
