### ISSUE TITLE
Agree Pantheon terminology

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#38]
What do we call the sample analysis page, etc

**Comment by johnvanbreda** [comment]
Terminology for OSIRIS:
Ecological division -> Broad biotope
Habitat -> Specific biotope
Traits -> Resources

Use CSS styling to consistently style each of these levels differently.
Traits that have children - use a + icon to indicate presence of children.

**Comment by johnvanbreda** [comment]
Andy - I've run the following query on the database to fix attribute names:

```
update taxa_taxon_list_attributes set caption = 'broad biotope' where id=5;
update taxa_taxon_list_attributes set caption = 'specific biotope' where id=6;
update taxa_taxon_list_attributes set caption = 'resource' where id=7; -- this one was already correct
```

**Comment by andrewvanbreda** [comment]
I will make the assumption that I need to make these changes to the importer unless I hear otherwise

**Comment by HDean** [comment]
There will some changes to the trait names. I need to make some changes to the documentation first but will let you have them ASAP.

**Comment by andrewvanbreda** [comment]
Hi,

Am just working out what I need to change in the importer. I can change the importer to cover John's database changes above. However I am unsure of some things.
1. I can see somethings in the importer that are not covered by the SQL above, for instance there is a termlist called "ecological division/habitat/resource"

should this be changed to the following?

"broad biotope/specific biotope/resource"

This question also applies to anything else I might find that needs changing.
1. 
   There are references to habitat in the importer in other places which are not a reference to the ecological division/habitat/resource hierarchy.
   For example there are quality indicies called "seepage habitats fidelity score".
   Am I correct in thinking these don't need changing.

**Comment by andrewvanbreda** [comment]
sorry Github has messed with the question numbering

**Comment by andrewvanbreda** [comment]
I have made the changes I believe were required for the importer. These are the change of names for the Ecological Division and Habitat attributes but also I changed the name of the 'ecological division/habitat/resource' termlist to 'broad biotope/specific biotope/resource' which is something not covered by John's SQL above but I assumed needed doing.
In order for the importer to work, I also had to change some of the data in the data files that I was supplied as the trait types were now wrong. 
Note I have only changed the name of that termlist and the attributes. Any reference to the word "habitat" in the data itself have not been altered. Also the word trait has been left as is as we were already using the word "resource". 
So there are still references to the word trait in the column headings in the data file for instance (such as "TraitType")
Is it the plan to alter these references also?

**Comment by HDean** [comment]
Hi Andy,

The column headings will not change, so any name with Trait in it will remain as Trait.

**Comment by HDean** [comment]
Database now updated with changes to traits, etc.

**Comment by johnvanbreda** [comment]
> I can see somethings in the importer that are not covered by the SQL above, for instance there is a termlist called "ecological division/habitat/resource" should this be changed to the following? "broad biotope/specific biotope/resource"

Yes, I think it makes sense to change the termlist title to keep things consistent, though its not going to be displayed to the end user so doesn't really matter.

> There are references to habitat in the importer in other places which are not a reference to the ecological division/habitat/resource hierarchy. For example there are quality indicies called "seepage habitats fidelity score". Am I correct in thinking these don't need changing.

Correct, I don't think you change these in the importer unless Hannah chooses to change the trait names in the source DB.

**Comment by andrewvanbreda** [comment]
That is OK then as these changes have already been made and are as agreed above.

**Comment by HDean** [comment]
[20160915_PantheonHierarchies.docx](https://github.com/BiologicalRecordsCentre/Pantheon/files/486730/20160915_PantheonHierarchies.docx)

Hierarchy showing the traits structure for Osiris/ISIS attached.

**Comment by HDean** [comment]
Closing issue as new hierarchies have been incorporated into Pantheon and are now in use within the reporting.
