### ISSUE TITLE
Cut-and-paste data entry - Analysis Scratchpad

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/Pantheon#4]
Develop web interface to allow user to input a species list (taxon names or TVKs) and then run the Pantheon output (minus the sample overview).  

Accessible via menu: Add Data -> Enter species list 

JvB estimated 2 days effort

**Comment by johnvanbreda** [comment]
Add a tab to the standard Explore tool (Analysis Scratchpad). Contains a list of species names in a box. 
Ability to add rows from the other grids into this list. E.g. add a whole taxon group (filtered to those visible on the current report, e.g. on the current site boundary you are exploring). 
The scratchpad can be typed into or paste into for adding additional names.
Option to clear the scratchpad.
Option to match names on the scratchpad, any not matched are simply reported back to you to fix.
Ability to access the scratchpad as a standalone
Ability to run the list of species in the scratchpad into the analysis.

**Comment by johnvanbreda** [comment]
Further requirement - matching can be exact, or using search algorithm from iRecord (i.e. case tolerant, punctuation tolerant, and a few simple letter tolerances like ae=e).
