### ISSUE TITLE
Clarify what a user account will entail

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#40]
What access to records, etc.

**Comment by HDean** [comment]
Anything that is uploaded and saved will be made available through iRecord/rest of Pantheon.

Data entered into the scratchpad will not be saved and will not be available to anyone else.

**Comment by HDean** [comment]
Added Jon W's notes on user accounts and data flow
[20180812_UserAccount&DataFlow.pptx](https://github.com/BiologicalRecordsCentre/Pantheon/files/417711/20180812_UserAccount.DataFlow.pptx)

Current thoughts are:
- accounts are private and there is an option of being able to share and make data available to iRecord and NBN.

**Comment by johnvanbreda** [comment]
This area needs a bit of discussion I think, as the emphasis here seems to lean away from the generally preferred default position of "open unless there is a good reason not to be". 
There is an option in Indicia to prevent a user's records being accessed from outside the confines of a site (i.e. the user can effectively disable sharing with iRecord's reporting and verification). This would also prevent records appearing in NBN downloads if done via the current iRecord->NBN process, but if the NBN extraction is done directly from Pantheon it will make no difference.

**Comment by HDean** [comment]
From various discussions with David R and Jon W:

Species lists are loaded on the scratch pad and analyses run, option to save or discard.
If saved, data will be open, go through to iRecord and then to the NBN.

However, can it work the other way round, i.e. if species records have already been added to iRecord, can they be pulled through to Pantheon?
Also, there is a problem of possibly duplicating data on the NBN if data are already available via the NBN gateway and the same species list is loaded into Pantheon and saved.

**Comment by HDean** [comment]
There is currently no link to iRecord and it is not envisaged it will be in the near to medium future.
