### ISSUE TITLE
Structure the Lexicon

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/Pantheon#41]
The Lexicon will contain a large amount of freely formatted text. In addition there will be an element of the lexicon which is a structured dictionary of the various terms in the Pantheon data with text descriptions etc. 
Add content types to Drupal to support the Lexicon data
Add view output to the Lexicon
Add links to the various parts of the system to show the Lexicon output texts (e.g click on a habitat name to show a description of the habitat).

**Comment by johnvanbreda** [comment]
As a demonstration, I've set up a Drupal vocabulary called lexicon which can contain terms with descriptions (http://www.brc.ac.uk/pantheon/admin/structure/taxonomy/lexicon). 
Any report tagged as "lexicon enabled" will automatically put hints onto words from the lexicon using the description from the taxonomy. You can see this working for grassland & scrub matrix at http://www.brc.ac.uk/pantheon/osiris/tabular?dynamic-sample_id=471196#. 

The problem with this approach is the hints are plain text, so we might need something like a proper popup if you want formatting. Also if the lexicon terms are going to contain references etc, then we all want to use a content type rather than a taxonomy so we have more control over the structure.

Needs further discussion.

**Comment by johnvanbreda** [comment]
After discussion in teleconference:
Add a new content type called Lexicon, with fields for the term, brief description, body text (ability to insert images), links. 
Lexicon terms in reports show brief description as tooltip, with an i icon the right which links to the full page.
Add a Lexicon view which allows an easy search of the terms.

**Comment by johnvanbreda** [comment]
@HDean I've added the Lexicon content type so you can add a few terms. It is working on this page http://www.brc.ac.uk/pantheon/osiris/tabular?dynamic-sample_id=471196 so you can check things. I've not yet implemented the info icon which will link to the full page.
Do you want to be able to add images to the lexicon pages?

**Comment by johnvanbreda** [comment]
@HDean I've now enabled an i icon beside each linked term in the reports (only the tabular Osiris report at the moment) which should link to the lexicon page for the term. If you could fill in a few lexicon pages and let me know how it goes. I've also added a Lexicon link in the help menu which gives a searchable list of terms.

**Comment by HDean** [comment]
@johnvanbreda,
Looks good. Thanks for setting up the content type - hopefully I will be able to populate it this week,

**Comment by HDean** [comment]
Osiris, ISIS and Horus terms are now in the Lexicon
