### ISSUE TITLE
Input data from different recording dates to be analysed as one sample

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#43]
This would mean changing the current definitions of what is meant to by sample in Indicia. Suggesting leaving the structure as it currently is and using the scratchpad to combine the data from different dates into one analysis.

**Comment by HDean** [comment]
John, can you check that my notes above are correct. My notes on this from yesterday's meeting didn't make much sense but the above is what I think was the gist of the discussions.

**Comment by johnvanbreda** [comment]
Yes that's right - once we develop the scratchpad we can achieve this.

**Comment by johnvanbreda** [comment]
Scratchpad allows this now.
