### ISSUE TITLE
Need to ensure SATs can be separated from Osiris resources

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/Pantheon#46]
@andrewvanbreda I understand that the SATs from ISIS are going to merge into the Osiris hierarchy so will become children of the existing broad and specific biotopes in Osiris. This means that a single specific biotope might contain some children which are SATs and some which are resources. How will I tell them apart for output purposes?
Presumably the specific assemblage type attribute will still link these to their respective species (so they can be distinguished from resource attributes)?
Will the SAT terms end up in the existing termlist (which used to be called "ecological division/habitat/resource)? In which case could the source identify which are SATs and which are resources?

**Comment by andrewvanbreda** [comment]
Yes, the plan is to put them in among all the resources in that termlist hierarchy.
The source field on the termlists_terms is already in use though to list the origin of the item ISIS,OSIRIS,HORUS
I hadn't planned to still have a separate Specific Assemblage Type attribute on the import. However that idea appeals to me and could work nicely, to keep that as a separate attribute and point to items in the merged termlist.

Another possibility is that we could take advantage of something that will be developed for the Plant Portal project (we spoke about this a few months back), the plan is to introduce term (termlist_term) attributes. This could hold the type of the term whether it is a Specific Assemblage Type.
Having said that, I like the idea of keeping the Specific Assemblage Type attribute so this wouldn't be needed I think.

**Comment by johnvanbreda** [comment]
I agree - a SAT attribute would be the best approach. In fact I note that the data currently loaded contain an attribute ID 11, called 'specific assemblage type'.

**Comment by andrewvanbreda** [comment]
Hi John,

I have been just trying to clear up the situation regarding the specific assemblage types in regards to the importer, as that appears to be the main area of confusion as far as the data structure of the importer is concerned.

I am now really writing this down to give anyone a chance to shout "Wrong!" to me if needed as what I describe is now the way the importer is operating.

As Hannah mentioned to me in an email. the Specific Assemblage types are now nested under broad and specific biotopes/habitats.

This has caused a few elements of confusion.

A.
To give a specific example, there is a resource called "fungal fruiting bodies", that is a resource and also a specific assemblage type.
There both have the same parent (DW1 Decaying Wood), although the trait codes are different.
However if you look into the hierarchy that is stored in the termlist, it looks strange as there are two terms with identical names. 
This threw me, as it looked wrong.
I did contact Jon about this, and he send me some screenshots showing the display of ISIS specific assemblage types to always be in a different place to the rest of the OSIRIS hierarchy on screen.
What he has said there is correct, but I think what I said was also correct as Jon was talking about the on-screen display of data whereas I am referring to the data structure which, more often that, not is different.

I think the main point I am making here is that are happy to have more that one term with the same name in the termlist hierarchy in this way? (the trait codes are different and are held as synonyms). I am currently assuming there is no problem with this

B. The second point is the issue you raised if these are all now in the same hierarchy in the database, then how do we tell which are specific assemblage types. A suggestion was to use a separate attribute.
One of the early suggestions you made was to use the resource field and I said this was already in use.
However I made that comment having not worked on the project for a few months. The resource is in use, but only for ISIS for the specific assemblage types and OSIRIS for all the other broad biotopes/habitats/resources.
So you can see whether it is a specific assemblage type by simply looking at the resource to see if it is ISIS or not.
Given that do we even need a separate attribute? Wouldn't that complicate matters having two attributes pointing at the same termlist.
We know an ISIS resource is a specific assemblage type.
Also, it is a bit weird having a second attribute pointing at a termlist that it can only partially use.
Having said that it might make it simpler in some ways to have a separate attribute.
Please let me know which you wish to go ahead with (one attribute or two)

**Comment by johnvanbreda** [comment]
A. There is no reason why a SAT term could not be the same as an Osiris resource, in fact I can see that is true of the data currently loaded on the warehouse. Therefore when you merge the hierarchies you are quite likely to end up with a termlist that has 2 copies of some terms under a parent, one sourced from Osiris and one from ISIS. The difference will be that one is linked to its species via an attribute called Resource and one will be via an attribute called specific assemblage type or SAT. In fact, you could potentially have only 1 term and delete the duplicate so both point to the same term, but that might make things difficult if you did go down the route of tagging the terms differently as in your point B.

B. I'm not sure what you mean by the resource field? Won't it be easier for my queries if there are 2 different attributes (I don't think I care that they point at the same termlist). Though if you can explain what you mean by the resource field I might see your point better.

**Comment by andrewvanbreda** [comment]
A. Yes I don't think one term would work as well as the trait codes are different, if they were actually identical in every way then one term would be way to go.
Also the importer automatically builds the termlist and does so under the assumption that all these things are separate terms. So changing that logic would need quite a big retest.

B. Sorry, I am getting the column name wrong. I was referring to the source (source_id) field in the termlists_terms table. This would point to either OSIRIS or ISIS so you could see whether it was a specific assemblage type by checking for ISIS even if we didn't use a separate attribute. If you think it is simpler or better to use a separate attribute still, then I don't have any issue with that

**Comment by johnvanbreda** [comment]
A. Ok
B. A different attribute is easier for me, since the source is not in the cache_termlists_terms table so I'd need more joins.

**Comment by andrewvanbreda** [comment]
Ah OK, no problem

**Comment by HDean** [comment]
Hi @johnvanbreda,

Is this now sorted? As we are reporting the SATs separately I guess we have some satisfactory way of identifying the SATs? 

If you are happy with how this currently works, can you close the issue please.

Thanks, Hannah

**Comment by johnvanbreda** [comment]
Agreed, Andy has set up the importer with a separate attribute for SATs and resources so this is fine.
