### ISSUE TITLE
Species Index: add in a row count at the top of the page so it is easy to see the numbers of species selected

### ISSUE THREAD

**Issue by jonrwebb** [BiologicalRecordsCentre/Pantheon#47]

**Comment by johnvanbreda** [comment]
Is this for the full species index page (http://www.brc.ac.uk/pantheon/species-index), or the species lists generated for a sample (or when you click on the numbers for a trait)?
If the former, then do you simply want the row count currently shown in the table footer to also appear above the table?
If the latter, then do you simply want the standard summary info panel for a sample to be shown above the table?

**Comment by HDean** [comment]
Hi @johnvanbreda,
I think it is the former - the row count that is at the bottom of the table to appear above the table.

**Comment by johnvanbreda** [comment]
Ok, I've cloned the whole pager to the top. How's that?

**Comment by HDean** [comment]
Looks good to me. @jonrwebb - what you do think?

**Comment by HDean** [comment]
From discussions with Jon this morning, he is happy with this.

**Comment by jonrwebb** [comment]
Yep- all good

J
