### ISSUE TITLE
Species Index: chnage column header 'Specific Biotope' to 'Habitat'

### ISSUE THREAD

**Issue by jonrwebb** [BiologicalRecordsCentre/Pantheon#49]

**Comment by HDean** [comment]
Hi @jonrwebb,

In our meeting back in May we decided that habitats were going to be changed to specific biotope (see #38 ). Do you want it changed back to habitat?

**Comment by johnvanbreda** [comment]
See #38. We'd agreed that the Osiris hierarchy would be broad biotope > specific biotope > resource.

**Comment by jonrwebb** [comment]
Since then we have added ISIS Specific Assemblage Types, which may get confused with 'Specific Biotope'. Therefore let us change them to ‘Habitats’ for the time being.

I want the peer review to comment on this nomenclature as well

J

**Comment by jonrwebb** [comment]
Since then we have added ISIS Specific Assemblage Types, which may get confused with 'Specific Biotope'. Therefore let us change them to ‘Habitats’ for the time being. That means we have…

Borad Biotopes
Habitats
SATs
And all the other Traits and resources

I want the peer review to comment on this nomenclature as well; it would be great if someone came up with a better clutch of names

J

**Comment by johnvanbreda** [comment]
Ok. @andrewvanbreda I propose that we don't keep changing our code until the nomenclature is finalised - I'll just modify the output labels on the reports.

Being picky aren't these biotopes, not habitats? I.e. they don't relate to a specific population of a species, but a community. See https://en.wikipedia.org/wiki/Biotope.

**Comment by jonrwebb** [comment]
Hey John, please feel free to be picky.

Yes they are probably are biotopes and not habitats; we have misused the latter term grossly over the last few decades – but I needed something that would not get confused with other terms now ISIS Specific Assemblage Types are included (I felt having both these and Specific Biotopes would get complicated).

Can we call them habitats for now but as part of the Peer review we can ask for people’s thoughts on this nomenclature. I presume it is not difficult to change back and forth from Specific Biotope to Habitat to Another?

**Comment by andrewvanbreda** [comment]
I already changed the importer code a couple of weeks back, I can change it back again to habitat if you wish

**Comment by johnvanbreda** [comment]
@jonrwebb Although its not too tricky to change these names internally (e.g. in the importer and the reporting code) if we change them back and forth it will chip away at the time available disproportionately. So I'd suggest that Andy and I change nothing apart from the actual labels output on the reports. This means there might be a mismatch between the report output and the internal code but for the purposes of the peer review I don't think it matters. Once terminology is finalised we can tackle the task of correcting everything to match once and for all.

**Comment by jonrwebb** [comment]
Shouldn't be too much of a problem.

## 

Yes please, for the time being, if it is no big

**Comment by jonrwebb** [comment]
Ok, whatever you suggest. This will finalise when the peer review is complete. At this point I will expect a number of changes to terms and names

Thanks

Jon
