### ISSUE TITLE
Habitats and Resources that classed as Quality Indicators clearly marked

### ISSUE THREAD

**Issue by jonrwebb** [BiologicalRecordsCentre/Pantheon#52]
Only to be acted upon after Peer review, but all Osiris Habitats and Resources that are to be defined as quality indicators need to be clearly seen as such on all displays (tabular, hierarchy etc etc). Probably a December / Jan job.

**Comment by HDean** [comment]
I'm closing this for now. The peer review suggested that the quality indicators didn't really add anything. Can be reopened if needs be.
