### ISSUE TITLE
Tab colour on Tabular Hierarchy

### ISSUE THREAD

**Issue by jonrwebb** [BiologicalRecordsCentre/Pantheon#54]
Tab colours could do with matching phase 1 habitat types or similar (green for woodland; oranage for open habitats etc) review after Peer review

**Comment by johnvanbreda** [comment]
Before I change anything, you might not be aware but the colours chosen were selected for maximum colour contrast, to make it easier to see the difference especially if you have difficulty seeing certain colours. There's a paper about the list of colours we are using at http://www.iscc.org/pdf/PC54_1724_001.pdf if you are interested.

**Comment by johnvanbreda** [comment]
Closing - the tabular hierarchy has been removed.
