### ISSUE TITLE
Make location name a mandatory attribute on importing CSV files

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#55]
When importing data to Pantheon via the CSV import procedure, there are currently three attributes that are mandatory:
- Species
- Date
- Grid reference or other spatial reference

Jon Webb has requested that Location name should also be made mandatory when importing, to match the situation with entering records direct.

**Comment by HDean** [comment]
Hi @johnvanbreda 
Is it possible to have the same metadata fields for the CSV upload as those for the paste species list (see #131)?

**Comment by johnvanbreda** [comment]
Hi @HDean, the fields should already be available in the drop downs containing the list of fields you can map to in the Indicia database. Look near the bottom of the list under Sample custom attributes for example.

**Comment by johnvanbreda** [comment]
Fixed after next release - the warehouse will have the ability to flag core fields like the location name as required.
