### ISSUE TITLE
Add grouped traits to Osiris reporting

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#56]
Add groups of traits into the Osiris reporting.

To be discussed at the peer review in December 2016 - workshop session:
Grouped Traits: are there groups of habitats and traits that can usefully be picked out and highlighted from the overall Pantheon categories, e.g. in order to report on all the habitats/traits associated with brownfield sites, or with freshwater systems, etc.?

**Comment by HDean** [comment]
Grouped conservation traits attached.
[Grouped Conservation Trait 3.docx](https://github.com/BiologicalRecordsCentre/Pantheon/files/551055/Grouped.Conservation.Trait.3.docx)

**Comment by HDean** [comment]
Hi @johnvanbreda 
Earlier on in the month we discussed grouped traits and you were going to create a prototype for demonstration at the peer review using the river example (in the document attached above). Are you still able to do this?
Thanks, Hannah

**Comment by johnvanbreda** [comment]
This done, now pending feedback from the review.

**Comment by HDean** [comment]
Hi @johnvanbreda 
The decision has been made to put the grouped traits on hold for this FY (whilst useful there are other things to sort out in Pantheon that are a priority). Can you remove the filter that exists within the Habitats and resources (Osiris)? We are likely to revisit this next FY if we get additional funding.

**Comment by johnvanbreda** [comment]
Ok, I've hidden the controls rather than removed them completely.

**Comment by HDean** [comment]
Great. I'll close this issue for now. We can always reopen it if necessary.
