### ISSUE TITLE
Hover-over for the filtering in Species Index covers the filter text box

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#58]
When clicking in the text box at the top of the Species Index to filter the table, the hover-over containing details about the wild card sometimes gets in the way. It appears to happen towards to the right of the screen, when you are wanting to filter Resources and Traits, SAT codes, or the Horus column. You can still add text but you can't see what you are typing.

Is it possible to move the hover-over to below the filter text box?

**Comment by johnvanbreda** [comment]
Yes - I've fixed this in the code and will deploy to the site later.

**Comment by johnvanbreda** [comment]
Code now deployed to the site so this should be OK.
