### ISSUE TITLE
Add number of species field to all reports

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/Pantheon#6]
http://www.brc.ac.uk/pantheon/explore/all-samples

Add field for number of species within Sample

**Comment by HDean** [comment]
Updated this issue to include all reports rather than just the "explore all samples" page.

**Comment by johnvanbreda** [comment]
Please can you provide more details about exactly which reports need the extra column.

**Comment by HDean** [comment]
Number of species is already included in:

Summary
Horus summary

That would then leave the following to have somewhere in the output total number of species:

ISIS output
Osiris output

and in the overview table for "explore all samples"

**Comment by johnvanbreda** [comment]
Both the "ISIS assemblage summary" and "Osiris traits summary" currently show squares representing each trait, already containing the number of species. Likewise on the combined summary button, both sets of outputs already show species counts. Am I missing another report where they do need to be added?

**Comment by HDean** [comment]
I think what NE is the overall number of species that are being analysed. For the ISIS and Osiris summary reports, the number of species in the squares do not necessarily add up to the number of species overall in a sample, as not all species have data.

**Comment by johnvanbreda** [comment]
Done. I felt the best approach was to add the extra basic info from the summary panel (which includes the species count) onto the ISIS summary and to include the same summary panel on the OSIRIS summary for consistency. I've added a column to the samples list report.
