### ISSUE TITLE
not analysed species list link not correct

### ISSUE THREAD

**Issue by jonrwebb** [BiologicalRecordsCentre/Pantheon#60]
I also looked at Highgate Common and it has 80 species classed as ‘not analysed’. When I clicked on these I could not understand why they were not analysed…and then I realised that the list it was showing was the full species list form the site and not the 80. I think this might be a problem

**Comment by johnvanbreda** [comment]
No, I don't think that's the problem. There are indeed 80 taxa from the UKSI list loaded on the test warehouse which don't have any attributes on Pantheon but appear in that sample's list. Here's the list:

[species not in pantheon.txt](https://github.com/BiologicalRecordsCentre/Pantheon/files/561949/species.not.in.pantheon.txt)

There are a few reasons why this might be the case:
- The species genuinely aren't covered by Pantheon.
- The importer did not work properly (unlikely though as everything else is OK).
- The copy of UKSI in use on the test warehouse is not fully up to date so might have some glitches that could cause problems.
- The taxa are represented, but at a different level. For example, in the list you've got taxa such as Aphididae, or Ctenophthalmus (Ctenophthalmus) nobilis subsp. vulgaris Smit, 1955. It's possible that the species is covered but not the subspecies.

**Comment by jonrwebb** [comment]
Hi John,

I looked at this and agree that these species come from poorly known groups that we did not cover. The issue is that this list does not come up when you click on ‘not analysed’ tab in the window below. Instead it lists all the species in ‘Sample size’. I would have expected that if you click on the ‘not analysed’ species then it shows you just those 80. Is that clear? Thanks

[cid:image001.jpg@01D2338C.FD57BF70]

**Comment by HDean** [comment]
Hi @johnvanbreda 
A good example is sample ID 537899 - it says there are 13 species not analysed and when you click on the "13" you end up with a list of 152, which is the total number of species within the sample.
This is also the same for the number analysed. This samples says there are 139 analysed but by clicking on "139" it provides the entire list of species within the sample (152).

**Comment by johnvanbreda** [comment]
This is fixed.
