### ISSUE TITLE
Old conservation status should not show if the species has a new conservation status

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#63]
Some species may have an old and a new conservation status and where this occurs, only the new conservation status should be viewable.

If this is difficult to code, then the old conservation statuses will have to be removed.

The new conservation status is called "Great Britain Rarity Status". The old conservation status is called "Old Conservation Status".

An example: Abdera biflexuosa has an old conservation status of "Notable B" and a Great Britain rarity status of "NS". Only the "NS" should show against the species.

**Comment by johnvanbreda** [comment]
This change would make the query quite complex, though its possible I think. If the old statuses should only be displayed when there are no new statuses for the species, I suggest we remove them from the database to keep it simpler.

**Comment by HDean** [comment]
Designation data now updated so old conservation status has been removed where there is a new conservation status. Same file has been emailed to John.
[20161121_DesignationDataForPantheon.xlsx](https://github.com/BiologicalRecordsCentre/Pantheon/files/603180/20161121_DesignationDataForPantheon.xlsx)

**Comment by johnvanbreda** [comment]
Ok, this issue will become redundant when designations re-imported (imminent).
