### ISSUE TITLE
Reporting problems - contact us details

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#66]
We don't currently have a "contact us" button/page for users that get stuck.

I have also been informed that the email address that you receive when setting up an account is not suitable.

Should we have a specific mailbox for Pantheon. If so who will maintain/monitor it?

**Comment by johnvanbreda** [comment]
The email address provided when you set up an account should really be something@brc.ac.uk (so its the same domain as the website). I've changed it to pantheon@brc.ac.uk. You might need to ask with BRC (e.g. Jim or Biren) about setting up a monitored email address. We can of course easily add a Contact us page if required.

**Comment by HDean** [comment]
Thanks @johnvanbreda . I've requested an account from our IT department but the email address will be pantheon@ceh.ac.uk (we don't have any BRC domain email addresses). I'm still waiting for confirmation that IT are happy with this email address and I'll let you know when this has been set up.

**Comment by HDean** [comment]
Hi @johnvanbreda 
I now have an email account for pantheon@ceh.ac.uk.

**Comment by johnvanbreda** [comment]
@HDean I can't change the email address used for the registration process from something@brc,ac.uk because it has to match the site domain. I can make this one noreply@brc.ac.uk if you prefer so that people know it is not monitored?
Would you like to have a go at setting up a Contact Us page (just a basic page)? When done I guess it can be added to the Help menu.

**Comment by HDean** [comment]
@johnvanbreda 
I have set up a very basic contact us page. As there is no longer a "Help" item on the main menu, I have added it as a single item on the main menu. It has added it to the end so it comes after "Log out" which doesn't really make sense but I can't see how I can swap them over! Can you do this for me please?

**Comment by HDean** [comment]
@johnvanbreda 
I should have also asked if you can change the email address to noreply@brc.ac.uk in the email that is received when setting up an account. Thanks.

**Comment by johnvanbreda** [comment]
Done. An option might be to move Contact Us under the About menu item?

**Comment by HDean** [comment]
@johnvanbreda 
I did wonder about that but I wasn't sure if it was the best place for it. Is it usual to find a Contact Us page under About?

**Comment by johnvanbreda** [comment]
Probably not in retrospect. The current About menu is already a mixture of help and about content though so this area might benefit from a bit of thought. Perhaps leaving it as it is would be best, or changing the menu item from "Contact us" to just "Contact" would make the menu bar a tiny bit tidier.

**Comment by HDean** [comment]
"Contact us" changed to "contact"
