### ISSUE TITLE
Percentage representation differs between the different Osiris reports

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#68]
It has been noticed that the percentage representation between the three Osiris reports differ. The hierarchy and tabular hierarchy reports agree but differ from the tabular report.

**Comment by HDean** [comment]
Having just looked into this, I can't seem to replicate the problem.

**Comment by HDean** [comment]
Have asked for more details from Jon.

**Comment by HDean** [comment]
@johnvanbreda 
Hi John, there appears to be some differences between % representation between the hierarchy and tabular reports.

For example, sample ID 544896, in the hierarchy report tree-associated > arboreal shows 0% whilst in the tabular report it shows <1%.  And for tree-associated > decaying wood > sapwood and bark decay, in the hierarchy is shows 10% and in the tabular report is shows 11%.

Both reports are showing the same number of species.

**Comment by johnvanbreda** [comment]
Rounding mistakes - fixed.
