### ISSUE TITLE
Hide Osiris tabular hierarchy report from view

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#69]
Seems that most users are not bothered by the Osiris tabular hierarchy. This option should be removed from Pantheon but with the ability to reinstate if needed.

**Comment by HDean** [comment]
Hi @johnvanbreda,
Is this possible to do?

**Comment by johnvanbreda** [comment]
Done. 
To reinstate I'd need to uncomment the code on the Osiris options page as well as add the combined summary tag back to the combined summary tabular hierarchy report page.
