### ISSUE TITLE
Add in Species Quality Index (SQI) score

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#70]
The SQI is a simple score based on a mean rarity score for a sample.
The idea is to have an SQI in the species index (the rarity score for a species?) and then the calculated SQI for the species within the sample within each trait.

E.g. the SQI for tree-associated species, or the SQI for brackish pools and ditches species.

NB The rarity scores currently in the Pantheon database are not correct and are to be updated later.

**Comment by johnvanbreda** [comment]
1. When calculating the median, do I simply ignore any species that has no rarity score (there are about 2000 of these in the database at the moment)? This would mean that a sample containing 4 species, of which 3 are unscored and 1 is rarity 8, you would get an SQI of 8. 
2. Should the SQI be shown on all the Osiris output tabs? I.e. an SQI at the broad biotope level, the habitat level, resource level and for each SAT?

**Comment by HDean** [comment]
1. Good question, I will find out from Jon.
2. Yes. Jon would like the SQI added to the left of the Conservation Status. 

The SQI should be calculated as: sum all the scores for each species, then divide by the count, then multiply by 100. An example from Jon:

10 species
Scores of 1, 1, 1, 1, 1, 1, 1, 4,  4, 8 = 23
20 divided by the count (10)  = 2.30
X100  

SQI = 230

**Comment by johnvanbreda** [comment]
I've added the SQI column to the species index, species list for a sample and the Osiris tables. It currently completely ignores species with no rarity score (they are not included in the sum or the count). Let me know if this is wrong.

**Comment by HDean** [comment]
Question asked to JW on 22/12/2016 - Are species that don’t have a score ignored or included within the count of the species?

JW started conversation with Mark Gurney, provider of the scores, on 03/01/2017 to answer the question.

**Comment by HDean** [comment]
@johnvanbreda 
Anything that does not have a score should be ignored as they have not yet been created. Anything with a 0 should be included as these are mostly non-natives.

There are some new rarity scores coming very soon and I will pass them on as soon as I have them.

**Comment by johnvanbreda** [comment]
OK, that's how it works now so I'll close this.
