### ISSUE TITLE
Changes to pages following change to terminology

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#71]
Traits page:
http://www.brc.ac.uk/pantheon/explore/traits
Change "Osiris Broad Biotopes" to "Broad biotopes"
Change "Osiris habitats" to "Habitats"
Change "SAT" to "Specific Assemblage Type"

Species Index - and also applies to any of the species lists:
http://www.brc.ac.uk/pantheon/species-index
Delete "(Osiris)" from Broad biotope, Habitat and Resources column. 
Change "Resources and traits" to "Resources"
Change "ISIS SAT code" to "Specific Assemblage Type"
Change "Larval guild" to "Larval feeding guild"
Change "Adult guild" to "Adult feeding guild"

Change button names:
Change "Ecological guilds" to "Feeding guilds" - DONE
Change "Osiris" to "Habitats and resources" - DONE
Change "Horus" to "Habitat Scores" - DONE

**Comment by johnvanbreda** [comment]
Done

**Comment by HDean** [comment]
Sorry @johnvanbreda, I have noticed one that I/JW forgot to say!

In the species index and the species lists, "Published indices (HORUS)" should have the "(HORUS)" removed.

**Comment by johnvanbreda** [comment]
Also done
