### ISSUE TITLE
Changes to Resource names

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#73]
The names of the following resources should be changed:

"shelter" (S23) to become "shadiness"
"open" (S33) to become "light shade"
"shady" (S34) to become "heavy shade"
"freshwater pond" (W33) to become "shallow freshwater pond" (two instances, one is a child of W24, the other a child of W25)
"temporary water" (W44) to become "temporary water dependent" (two instances, one is a child of W33 >W24 and the other a child of W33>W25)

**Comment by HDean** [comment]
Hi @johnvanbreda 
How easy is it for you to change the above terms? If it is straightforward, can you let me know when it has been done and I can then update my database and the documentation.
Thanks, H

**Comment by johnvanbreda** [comment]
@hdean that's done. I've only updated our copy of the imported dataset, I'm assuming that you'll change the Access DB so any future imports will get the correct versions.

**Comment by HDean** [comment]
Access database updated, website pages and diagrams updated.
