### ISSUE TITLE
Resource to be removed from Pantheon

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#74]
The following resource should be removed from Pantheon (or at least not be visible!):

W43 shallow water 

This resource crops up in two places in the hierarchy, as a child of W33, which is a child of both W24 and W25.

**Comment by HDean** [comment]
@johnvanbreda 
Hopefully the above is not too tricky to do - it is not urgent so could be left if necessary.

**Comment by johnvanbreda** [comment]
Done.

For my own reference, here are the queries I used to check the values to delete and then do the actual deletion:

```
select * from taxa_taxon_list_attributes where caption='resource' -- 186

select * from cache_termlists_terms where term='shallow water'

select * from list_taxa_taxon_list_attribute_values where taxa_taxon_list_attribute_id=186 and raw_value in (
select id::varchar from cache_termlists_terms where meaning_id in (13158,13136)
)

update taxa_taxon_list_attribute_values set deleted=true, updated_on=now() where taxa_taxon_list_attribute_id=186 and int_value in (
select id from cache_termlists_terms where meaning_id in (13158,13136)
)
```
