### ISSUE TITLE
Conservation status of "none" not to show in reports

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#75]
Similar to Least Concern, if a species has a conservation status of "none" these should not show in the reports.

None as a conservation status should still show in the species index and species lists.

**Comment by HDean** [comment]
Sorry @johnvanbreda 
This got missed by me. Hopefully this is quick to sort out. Not urgent!

**Comment by johnvanbreda** [comment]
Fixed.
