### ISSUE TITLE
ISIS compliance warning for condition assessment

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#76]
Within the SAT tab in the Habitats and resources tabular report, there is a "Reported condition" column which states if the sample is favourable or unfavourable. The confidence given to such as statement depends very much on the methods used to collected the sample.

David H has created a document that details 3 compliance categories and how the result should be interpreted depending on which category the samples falls under (see attached).
[ISIS Compliance in Pantheon.docx](https://github.com/BiologicalRecordsCentre/Pantheon/files/689888/ISIS.Compliance.in.Pantheon.docx)

**Comment by HDean** [comment]
@johnvanbreda 
How do we implement the above? I am thinking, if possible, that we can have some link from either "favourable" or "unfavourable", or from the column heading "Reported condition" that takes the user to a Lexicon page which details out the categories and confidence in the reported condition. The user makes the decision for themselves.
At present we don't ask for the method used in collecting the data and "time limited within prescribed areas" hasn't been defined, then this is not something that Pantheon can decide upon.

**Comment by johnvanbreda** [comment]
Agreed, if we don't have the information required in the Pantheon dataset, then there is very little we can do other than providing some helpful text in the Lexicon. Let me know if you want to do that from the column heading or the individual row condition values.

**Comment by HDean** [comment]
@johnvanbreda 
I suggest that we do it from the column heading. We can always review and update at a later date.

**Comment by johnvanbreda** [comment]
@HDean I've enabled lexicon links for an table column heading on the site. I've added a stub for the Reported condition one so you can test it - please update the basic text I provided.

**Comment by HDean** [comment]
@johnvanbreda 
I've updated the lexicon. Hover-over text pops up but the link from the "i" isn't activated.

**Comment by johnvanbreda** [comment]
Fixed.
