### ISSUE TITLE
Add associated species to the Species Index

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#77]
Associated species data should be added as an additional column to the Species Index.

**Comment by HDean** [comment]
Hi @johnvanbreda 
Jon would like the associated species data to be added to the Species Index. Is this possible and easy to do? If it is going to be difficult then I would recommend that we leave it for now.

**Comment by johnvanbreda** [comment]
Adding the code is not tricky. However there would be a performance impact (I'd guess it might take 20% longer to load) and also will we have an issue with the column not fitting on the page?

**Comment by HDean** [comment]
@johnvanbreda 
Fitting it on a page was one of my concerns too but Jon did say he would like it (and David H also sent me a message this afternoon saying he would like it added).
Jon did mention that we might remove some of the other columns instead.

With regards performance I will ask Jon and David H's opinion. I expect that it might be a case of adding it and then seeing how badly it affects performance.

**Comment by johnvanbreda** [comment]
Done. Performance does not seem to be massively affected.

**Comment by HDean** [comment]
Hi @johnvanbreda 
Looks good and I agree it doesn't really seem to affect performance massively.

Jon has got back to me with regards fitting it on the page. He has suggested removing the following columns from the initial view but with the option to add them through the "+":

1.	Larval and Adult feeding guild
2.	Specific Assemblage Type
3.	Published indices
4.	Resources 
5.	SQI 

Can the "SQI" be renamed to "SQS"  - Species Quality Score – the SQI is the combined score for each sample).

Jon would also like to have something at the top of the page that says: 
"More options are available to view by clicking on the ‘+’ sign"

Is this possible?

**Comment by johnvanbreda** [comment]
Yes, that's done.
