### ISSUE TITLE
Add headings to hierarchy boxes

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#78]
Add "Broad biotope", "Habitats" and "Resources" to the top of the page under which the relevant boxes show.

**Comment by HDean** [comment]
Hi @johnvanbreda 
Is adding headings to the hierarchy report possible? If it is but will take a disproportionate amount of time to add, then we will leave this for now.

**Comment by johnvanbreda** [comment]
Done

**Comment by HDean** [comment]
It is done but not showing correctly in Chrome.

**Comment by johnvanbreda** [comment]
Probably a caching issue in your browser cache - try Ctrl-F5.

**Comment by HDean** [comment]
All showing correctly now
