### ISSUE TITLE
ISIS SATs showing in resources within the hierarchy report

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#80]
The hierarchy report shows the SATs within the resourcse but they should not be there.

E.g. sample 312081, tree-associated > decaying wood
"fungal fruiting bodies" shows up twice - one is a resource, the other is a SAT. Only the resource should show.
"sapwood & bark decay" and "bark & sapwood decay" both show - the first is the resource and should be visible, the second is the SAT and should not be visible.

**Comment by johnvanbreda** [comment]
Done

**Comment by HDean** [comment]
All looks good
