### ISSUE TITLE
Add Sample Name to the header of each page, along with Sample ID

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#81]
Is it possible to add the sample name along with the sample ID at the top of each report page?

**Comment by johnvanbreda** [comment]
What do you define as the sample name? Date, placename, grid ref etc?

**Comment by HDean** [comment]
Good question!
Can we have a composite? So site name, date and grid ref?

**Comment by HDean** [comment]
Also Osiris is still showing up in the header and breadcrumb - can these be changed?
