### ISSUE TITLE
Resources in species lists to be shown under their subheadings

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#82]
Hi @johnvanbreda 
Is it possible in species lists for the resources column to show like that in the resources tab in the habitats and resources tabular report?
I.e. where the resource is actually a subheading, e.g. conifer or broadleaved, the resource under that subheading is shown alongside rather than underneath, e.g. conifer or broadleaved >> broadleaved only.

**Comment by johnvanbreda** [comment]
Done
