### ISSUE TITLE
"Info" buttons to open in new tab

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#83]
The small buttons labelled "i" that give links into the lexicon currently open up in the same window, which means that if you have been using a filtered list you lose your filters when you go back. Can we:
- make the default behaviour to open in a new tab
- show the summary lexicon text when hovering over the "i" button

**Comment by kitenetter** [comment]
Have now realised that the summary text does appear if you hover over the term itself, rather than over the "i" button. In an ideal world I think it would be better to have the hover text associated with the "i" button but that is not a big deal.

I would prefer the "i" button, when clicked, to open in a new tab though.

**Comment by johnvanbreda** [comment]
Both done
