### ISSUE TITLE
Add filter icon to temporary filter row at top of tables

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#85]
Tables such as the species index allow on-the-fly filtering, but this is not obvious to the user as the row under the table headings is completely blank. Is it possible to add a filter icon, and/or to put outlines round the grid squares in this row, to make it more obvious that it can be typed into?

![image](https://cloud.githubusercontent.com/assets/16039111/22343996/39be44c8-e3f2-11e6-96e7-c3759198d2d1.png)

**Comment by johnvanbreda** [comment]
Done.
