### ISSUE TITLE
Habitat scores sometimes show as error codes

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#86]
When clicking on the Habitat scores button, the summary page is sometimes just a load of error code. This does not happen for all samples. And where it does happen it always happens!

e.g. sample ID 552007
sample ID 545670
sample ID 312081

**Comment by johnvanbreda** [comment]
This happened in the case where there are ERS scores but all were >3 so were discarded in the calculation according to the rules in the help. 
@hdean I noticed in the help that only beetle scores should be included - should I be actively discarding non-beetle species scores then?

**Comment by johnvanbreda** [comment]
I've fixed the report BTW

**Comment by HDean** [comment]
HI @johnvanbreda 
The ERS for the Coleoptera are going to change so when the next import of the database is done the Sadler & Bell (2002) quality indices will be removed completely and replaced with Bates (2005).

The other ERS, Drake & Hewitt (2007), will remain the same.

**Comment by HDean** [comment]
I should also have said that the change from Sadler & Bell to Bates will mean that only beetles are included and they have a score of only 1 or 2.

**Comment by johnvanbreda** [comment]
Ok, thanks. For reference in future, when this change is made we will need to:

* Search and replace in the import scripts to change the references to S & B to B. 
* Update the habitat scores report to pick up the correct attribute.
