### ISSUE TITLE
"Habitats & resources: species list" report is duplicating records

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#87]
From the combined summary page, the "Habitats & resources: species list" table is showing all synonyms for both scientific and English names, e.g. the first five rows in this example are all the same single species record:

![image](https://cloud.githubusercontent.com/assets/16039111/22396241/0ab06c8c-e54c-11e6-82ab-e6bcc29c007a.png)

**Comment by HDean** [comment]
Hi @kitenetter 
I'm having trouble replicating this. What I can't do is find the "Habitats & resources: species list" on the combined summary.
Would you be able to provide me with a link to an example?

**Comment by kitenetter** [comment]
Ah, we removed "Habitats & resources: species list"! See #119
