### ISSUE TITLE
Combined summary tables: titles and column headings inconsistent

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#88]
From the combined summary page, there are some inconsistencies in the way that the tables are titled and headed:
- Table "Habitats & resources: broad biotopes"; uses heading "Broad biotope", which is correct
- Table "Habitats & resources: habitats"; uses headings "Broad biotope" and "Specific biotope" - the latter should be "Habitat"
- Table "Habitats & resources: resources and traits"; uses headings "Broad biotope", "Specific biotope" and "Resource" - "Habitat" should be used in place of "Specific biotope"
- Table "Habitats & resources: species list"; uses headings "Broad habitat" and "Specific biotope" - these should be "Broad biotope" and "Habitat" respectively, but this is a mismatch with the title of this table, so either the title should be "Habitats species list" or the table should include a column for "Resource"

**Comment by johnvanbreda** [comment]
Fixed.

**Comment by kitenetter** [comment]
Thanks for fixing on the website. The column headings in the CSV downloads (via the "download this report" link) are now not consistent with the display on the website (e.g. they still have "Specific biotope" in place of "Habitat".
