### ISSUE TITLE
Species table "+" button not working

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#89]
From the Combined summary page, the "Species" table has a "+" button that looks as if it will allow you to select a different set of columns to display, but in fact it isn't possible to change the columns, Not sure if this means that the "+" button functionality needs repairing, or if the "+" button should not be there.

![image](https://cloud.githubusercontent.com/assets/16039111/22396294/ff3d860e-e54c-11e6-9977-079efeb40809.png)

If you view this table via "Species list for sample" (rather than via the Combined summary) the "+" button does work, and this is currently the only way in which you can see which species has been associated with which feature - but this table cannot be downloaded.

Can we either fix the "+" button on the Combined summary table, or make the Species list for sample table downloadable (or both!).

**Comment by kitenetter** [comment]
In fact it appears that if you start from Combined summary and select *only* the species list option, the "+" button does work as expected. The problem only arises if you select the Species list in combination with other parts of the Combined summary.

**Comment by kitenetter** [comment]
Further to this, the columns that appear in the Species table in the Combined summary seem to vary - is the table 'remembering' a setting that has been used previously?

**Comment by johnvanbreda** [comment]
Fixed. 
Regarding the last point, the species list on the combined summary will share its column picker settings with the species list for a sample shown as a standalone report. The settings are remembered in a cookie, which reminds me shouldn't we add EU cookie compliance to the site?
