### ISSUE TITLE
Combined summary page - Select all option?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#90]
Would it be possible to have an option to select/unselect ALL the tick boxes on the combined summary page?

![image](https://cloud.githubusercontent.com/assets/16039111/22396379/46a8f3ea-e550-11e6-8244-1907da457920.png)

If that isn't possible, I would prefer to have all boxes selected by default, rather than all unselected as it is at the moment.

**Comment by HDean** [comment]
Not being done as part of this development phase.
