### ISSUE TITLE
Display of Features in downloaded tables

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#91]
#If you download "Habitats & resources: resources and traits" as a CSV, the "Resource" column gets displayed with "span" commands:
- `<span>habitats</span>` >> <span>sward/field layer</span>`

Can we remove the span commands from the download?

If you download "Species list" as a CSV, the "Resources" column gets displayed with numeric codes:
- `[[13831,0,"soil humidity"],[13837,0,"habitats"],[13867,13837,"sward/field layer"],[13947,13831,"dry"]]`

Also, in this view the labels get disassociated from their terms (e.g. "soil humidity" is separated from "dry" in the above example). Can the Species list Resource column be displayed in the same way as the "Habitats & resources: resources and traits" (but without the span commands!).

**Comment by kitenetter** [comment]
@HDean I know you said this was more of a presentation issue than a functionality one, it is an extremely annoying presentation issue! (That is, the `<span>` and `[[13831,0,"` codes.)

It results in much time being spent on data cleaning every time I use Pantheon, and is not a good advert when trying to enthuse others to make use of Pantheon. My vote is for high priority!

**Comment by HDean** [comment]
Hi @johnvanbreda ,
Hopefully this is fairly easy to amend? Although this doesn't affect functionality, I agree with Martin it doesn't look particularly good. If you think this is going to be a tricky one, then leave it for now, but if you think this is fairly quick to update, then please see this as a high priority one.

**Comment by johnvanbreda** [comment]
It is a bit tricky I'm afraid, because the formatting is performed in the code which draws the grid, rather than in the database queries which directly feed into the downloads.

**Comment by HDean** [comment]
Okay, hold fire on this one until the other high priorities are fixed.

**Comment by johnvanbreda** [comment]
Actually, this one becomes easier to fix once the changes for #172 are deployed. There is a new species_index table in the database with the output in both formatted and unformatted forms, so we can make use of this.

**Comment by johnvanbreda** [comment]
I've now integrated the new species index table in the list of species for a sample, so it is both much faster and fixes the formatting in the download. Still need to look at issues in habitat and resources.

**Comment by johnvanbreda** [comment]
Resources also fixed.
