### ISSUE TITLE
Conservation status needs to not show pLC in reports

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#92]
Apologies John, I missed this one. As well as LC not showing in the reports, pLC should also be excluded. These are provisionally Least Concern.
Thanks,

**Comment by johnvanbreda** [comment]
@HDean Should we also be removing pNA since we remove NA?

**Comment by HDean** [comment]
Yes, I think we should!

**Comment by johnvanbreda** [comment]
Done
