### ISSUE TITLE
"Dung & Carrion" not showing the split into "Dung" and "Carrion"

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#94]
In the hierarchy and tabular - other, the species for dung & carrion do not appear to be showing a split into just dung or just carrion.

**Comment by johnvanbreda** [comment]
It looks OK to me - can I have a specific example please @HDean?

**Comment by HDean** [comment]
Hi @johnvanbreda 
Sample ID 312081 show 20 species belonging to "dung & carrion". At least one of those species, for example Aphodius (Acrossus) rufipes, should also be showing dung & carrion >> dung. This is not showing in the hierarchy or tabular - other. It does show in the species index (when you add in the resources column).

**Comment by HDean** [comment]
Jon Webb also sent me this example:

Sample ID 312081 - there are 20 species that have "dung & carrion" but none show up in level two under just "dung" or just "carrion". If you look at the 20 "dung & carrion" species you will see that 12 species are just "dung" and 24 are just "carrion".

**Comment by johnvanbreda** [comment]
I think what is happening here is that the Dung & carrion entry under Other is showing only dung & carrion where the resource has no parent habitat, so you are only seeing part of what you expect. You can find dung and carrion under open habitats >> tall sward for example and in here it is possible to expand them out. 
@HDean am I right in thinking that the Dung and Carrion entry which appears under "Other" should be a total of ALL dung and carrion species even if they are typed within a specific habitat?

**Comment by HDean** [comment]
@johnvanbreda
Yes, that's correct - all dung & carrion species should show under other even if they are typed within a specific habitat. If they have also been split into just "dung" or just "carrion" they should show up within the level 2 tab too.

**Comment by johnvanbreda** [comment]
Ah, fixed, didn't spot that the script which creates the top level dung & carrion didn't also copy over the 2nd level.
