### ISSUE TITLE
Habitats grid not displaying in full

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#98]
Have just been looking at a large sample of just over 4,000 species:
http://www.brc.ac.uk/pantheon/osiris/tabular?dynamic-conservation_group_id=&dynamic-sample_id=678547&dynamic-sample_type=sample

The tabular view, using the "Habitats" tab, initially shows 20 Habitats on the first page of the grid. The counter at the foot of the grid rather unhelpfully says "Showing records 1 to 20 of 18". If I click on the "Next" button it appears to think about changing the page, but then re-displays the first 20 rows.

But if I "download this report" I get 53 rows of Habitats.

There are in fact only 20 unique Habitats represented in this sample, but 53 unique combinations of Broad biotope + habitat.

**Comment by johnvanbreda** [comment]
Fixed - same underlying issue as #99.
