### ISSUE TITLE
Odd duplications in Habitats table

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#99]
I don't understand why there are six rows here, with different totals in different rows - there should be just three rows with one consistent set of data shouldn't there?:

![image](https://cloud.githubusercontent.com/assets/16039111/22570693/524b9110-e994-11e6-8287-56e6c2bbccfa.png)

**Comment by johnvanbreda** [comment]
There was a missing link between the habitats and their parent biotopes, so you were getting all combinations of the 2 rather than just parent->child relationships. Surprised we didn't spot that before! Now fixed.
